(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["monitor"],{

/***/ "./src/routes/monitor/index.svelte":
/*!*****************************************!*\
  !*** ./src/routes/monitor/index.svelte ***!
  \*****************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _components_Menu_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../components/Menu.svelte */ "./src/components/Menu.svelte");
/* harmony import */ var _components_Monitor_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../components/Monitor.svelte */ "./src/components/Monitor.svelte");
/* harmony import */ var _components_Table_Table_svelte__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../components/Table/Table.svelte */ "./src/components/Table/Table.svelte");
/* harmony import */ var _components_FetchData_js__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../../components/FetchData.js */ "./src/components/FetchData.js");
/* harmony import */ var _components_UrlSearch_js__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../../components/UrlSearch.js */ "./src/components/UrlSearch.js");
/* src/routes/monitor/index.svelte generated by Svelte v3.23.2 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];






const file = "src/routes/monitor/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-hrxrjf-style";
	style.textContent = ".tab_margin.svelte-hrxrjf{margin-bottom:0.5em}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gXCJzdmVsdGVcIjtcbiAgaW1wb3J0IE1lbnUgZnJvbSBcIi4uLy4uL2NvbXBvbmVudHMvTWVudS5zdmVsdGVcIjtcbiAgaW1wb3J0IE1vbml0b3IgZnJvbSBcIi4uLy4uL2NvbXBvbmVudHMvTW9uaXRvci5zdmVsdGVcIjtcbiAgaW1wb3J0IFRhYmxlIGZyb20gXCIuLi8uLi9jb21wb25lbnRzL1RhYmxlL1RhYmxlLnN2ZWx0ZVwiO1xuICBpbXBvcnQgeyBGZXRjaERhdGEgfSBmcm9tIFwiLi4vLi4vY29tcG9uZW50cy9GZXRjaERhdGEuanNcIjtcbiAgaW1wb3J0IHsgVXJsU2VhcmNoIH0gZnJvbSBcIi4uLy4uL2NvbXBvbmVudHMvVXJsU2VhcmNoLmpzXCI7XG5cbiAgZXhwb3J0IGxldCBzZWdtZW50O1xuXG4gIGxldCBGRGF0YSA9IG5ldyBGZXRjaERhdGEoKTtcbiAgbGV0IHBhZ2VTZWxlY3RlZCA9IDA7XG4gIGxldCBwYXJhbXNNb25pdG9yID0geyBpZGRpdmlzaW9uOiAtMSB9O1xuICBsZXQgQ29sdW1uc01vbml0b3IgPSB7XG4gICAgaWRldmVudDogeyAgbGFiZWw6IFwiSURcIiB9LFxuICAgIGRhdGVldmVudDogeyAgbGFiZWw6IFwiRmVjaGFcIiwgdHlwZTogXCJEYXRlXCIgfSxcbiAgICBhY2NvdW50X25hbWU6IHsgbGFiZWw6IFwiVGllbmRhXCIgfSxcbiAgICBsYWJlbF9zdGF0dXM6IHsgbGFiZWw6IFwiRXN0YWRvXCIgfSxcbiAgICBwcmlvcml0eTogeyBsYWJlbDogXCJQXCIsIHR5cGU6IFwiUHJpb3JpdHlcIiB9LFxuICAgIGxhYmVsX2V2ZW50dHlwZTogeyBsYWJlbDogXCJFdmVudG9cIiB9LFxuICAgIGRlc2NyaXB0aW9uOiB7IGxhYmVsOiBcIkRlc2NyaXBjacOzblwiIH0sXG4gIH07XG5cbiAgbGV0IHBhcmFtc2RvY3VtZW50b3NfcG9yX2NvbnN1bHRhcl9lc3RhZG8gPSB7IGlkZGl2aXNpb246IC0xIH07XG4gIGxldCBDb2x1bW5zZG9jdW1lbnRvc19wb3JfY29uc3VsdGFyX2VzdGFkbyA9IHtcbiAgICBmZWNoYV9lbWlzaW9uOiB7ICBsYWJlbDogXCJFbWlzacOzbnhcIiwgdHlwZTogXCJEYXRlXCIgfSxcbiAgICBhY2NvdW50X25hbWU6IHsgbGFiZWw6IFwiVGllbmRhXCIgfSxcbiAgICBzZXJpZV9kb2N1bWVudG86IHsgbGFiZWw6IFwiRG9jdW1lbnRvXCIgfSxcbiAgICBpZGVudGlmaWNhdGlvbjogeyBsYWJlbDogXCJDb2QuIFNBUFwiIH0sXG4gICAgdGlwb19kb2N1bWVudG86IHsgbGFiZWw6IFwiVGlwb1wiIH0sXG4gICAgbWF0cml6OiB7IGxhYmVsOiBcIk1hdHJpelwiLCB0eXBlOiBcIkJvb2xlYW4tQ29sb3JcIiB9LFxuICAgIGVudmlhZG86IHsgbGFiZWw6IFwiRW52aWFkb1wiLCB0eXBlOiBcIkJvb2xlYW4tQ29sb3JcIiB9LFxuICAgIGF1dG9yaXphZG86IHsgbGFiZWw6IFwiQXV0b3JpemFkb1wiLCB0eXBlOiBcIkJvb2xlYW4tQ29sb3JcIiB9LFxuICAgIGNhcjogeyBsYWJlbDogXCJDYXJcIiwgdHlwZTogXCJCb29sZWFuLUNvbG9yXCIgfSxcbiAgfTtcblxuICAvL2FjY291bnRfbmFtZSwgYWNjb3VudCwgaWRlbnRpZmljYXRpb24sIGVuX3B2LCBlbl9tYXRyaXosIGVudmlhZG9zICwgYXV0b3JpemFkb3MsIGVuX2NhclxuICBsZXQgQ29sdW1zRG9jc1Jlc3VtZW5Ib3kgPSB7XG4gICAgYWNjb3VudF9uYW1lOiB7IGxhYmVsOiBcIlRpZW5kYVwiIH0sXG4gICAgaWRlbnRpZmljYXRpb246IHsgbGFiZWw6IFwiQ29kLiBTQVBcIiB9LFxuICAgIGVuX3B2OiB7IGxhYmVsOiBcIlBWXCIgfSxcbiAgICBlbl9tYXRyaXo6IHsgbGFiZWw6IFwiTWF0cml6XCIgfSxcbiAgICBlbnZpYWRvczogeyBsYWJlbDogXCJFbnZpYWRvc1wiIH0sXG4gICAgYXV0b3JpemFkb3M6IHsgbGFiZWw6IFwiQXV0b3JpemFkb3NcIiB9LFxuICAgIGVuX2NhcjogeyBsYWJlbDogXCJDYXJcIiB9LFxuICB9O1xuXG4gIGxldCBDT0xVTU5TX21vdmludl9wZW5kaWVudGVzX2NhcmdhciA9IHtcbiAgICBhY2NvdW50X25hbWU6IHsgbGFiZWw6IFwiVGllbmRhXCIgfSxcbiAgICAvL2FjY291bnQ6IHsgaGlkZGVuOiB0cnVlIH0sXG4gICAgYnVrcnM6IHsgbGFiZWw6IFwiYnVrcnNcIiB9LFxuICAgIGJ3YXJ0OiB7IGxhYmVsOiBcImJ3YXJ0XCIgfSxcbiAgICAvL2NwdWR0OiB7IGhpZGRlbjogdHJ1ZSB9LFxuICAgIC8vY3B1dG06IHsgaGlkZGVuOiB0cnVlIH0sXG4gICAgc2hremc6IHsgbGFiZWw6IFwic2hremdcIiB9LFxuICAgIG1hdG5yOiB7IGxhYmVsOiBcIm1hdG5yXCIgfSxcbiAgICBtYmxucjogeyBsYWJlbDogXCJtYmxuclwiIH0sXG4gICAgbWVuZ2U6IHsgbGFiZWw6IFwibWVuZ2VcIiB9LFxuICAgIHdlcmtzOiB7IGxhYmVsOiBcIndlcmtzXCIgfSxcbiAgICBkYXRldGltZWZpbGU6IHsgbGFiZWw6IFwiRmVjaGFcIiwgdHlwZTogXCJEYXRlXCIgfVxuICB9O1xuXG4gIC8vY29uc29sZS5sb2coQ29sdW1uc01vbml0b3IpO1xuICBmdW5jdGlvbiBDaGFuZ2VQYWdlKHBhZ2VJZCkge1xuICAgIHBhZ2VTZWxlY3RlZCA9IHBhZ2VJZDtcbiAgICBjb25zb2xlLmxvZyhwYWdlU2VsZWN0ZWQpO1xuICB9XG5cbiAgZnVuY3Rpb24gQ2xpY2tWZWhpY2xlU2VsZWN0ZWQoaWQpIHtcbiAgICBjb25zb2xlLmxvZyhpZCk7XG4gICAgd2luZG93LmxvY2F0aW9uLmhyZWYgPSBcIi9ob21lXCI7XG4gIH1cblxuICBvbk1vdW50KGFzeW5jICgpID0+IHtcbiAgICBwYXJhbXNNb25pdG9yLmlkZGl2aXNpb24gPSBVcmxTZWFyY2goXCJpZGRpdmlzaW9uXCIpO1xuICAgIHBhcmFtc2RvY3VtZW50b3NfcG9yX2NvbnN1bHRhcl9lc3RhZG8uaWRkaXZpc2lvbiA9IHBhcmFtc01vbml0b3IuaWRkaXZpc2lvbjtcbiAgICAvL2NvbnNvbGUubG9nKHBhcmFtc01vbml0b3IpO1xuICAgIHBhZ2VTZWxlY3RlZCA9IDE7XG4gIH0pO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgLnRhYl9tYXJnaW4ge1xuICAgIG1hcmdpbi1ib3R0b206IDAuNWVtO1xuICB9XG4gIC8qICAuaWNvbl9saW5rIGEge1xuICAgIGNvbG9yOiB3aGl0ZTtcbiAgfVxuXG4gIC5pY29uX2xpbmsgYTpob3ZlciB7XG4gICAgY29sb3I6IHJnYigyNTUsIDEwMiwgMCk7XG4gIH0qL1xuPC9zdHlsZT5cblxuPE1lbnUge3NlZ21lbnR9PlxuICA8c3BhbiBzbG90PVwiVGl0bGVcIj5cbiAgICA8aSBjbGFzcz1cImZhcyBmYS1zaGllbGQtYWx0XCIgLz5cbiAgICBPUEVOIE1PTklUT1JJTkcgU1lTVEVNXG4gIDwvc3Bhbj5cblxuPC9NZW51PlxuXG48ZGl2IGNsYXNzPVwidGFicyBpcy1zbWFsbCB0YWJfbWFyZ2luXCI+XG4gIDwhLS0gc3ZlbHRlLWlnbm9yZSBhMTF5LW1pc3NpbmctYXR0cmlidXRlIC0tPlxuICA8dWw+XG4gICAgPGxpIGNsYXNzOmlzLWFjdGl2ZT17cGFnZVNlbGVjdGVkID09PSAxfT5cbiAgICAgIDxhIG9uOmNsaWNrPXsoZSkgPT4gKHBhZ2VTZWxlY3RlZCA9IDEpfT5FdmVudG9zPC9hPlxuICAgIDwvbGk+XG4gICAgPGxpIGNsYXNzOmlzLWFjdGl2ZT17cGFnZVNlbGVjdGVkID09PSAyfT5cbiAgICAgIDxhIG9uOmNsaWNrPXsoZSkgPT4gKHBhZ2VTZWxlY3RlZCA9IDIpfT5cbiAgICAgICAgRmFjdC4gRWxlY3Ryw7NuaWNhIC0gUmVzdW1lbiBIb3lcbiAgICAgIDwvYT5cbiAgICA8L2xpPlxuICAgIDxsaSBjbGFzczppcy1hY3RpdmU9e3BhZ2VTZWxlY3RlZCA9PT0gM30+XG4gICAgICA8YSBvbjpjbGljaz17KGUpID0+IChwYWdlU2VsZWN0ZWQgPSAzKX0+XG4gICAgICAgIEZhY3QuIEVsZWN0csOzbmljYSAtIERvY3VtZW50b3MgUGVuZGllbnRlc1xuICAgICAgPC9hPlxuICAgIDwvbGk+XG4gICAgPGxpIGNsYXNzOmlzLWFjdGl2ZT17cGFnZVNlbGVjdGVkID09PSA0fT5cbiAgICAgIDxhIG9uOmNsaWNrPXsoZSkgPT4gKHBhZ2VTZWxlY3RlZCA9IDQpfT5Nb3YuIEludi4gUGVuZGllbnRlczwvYT5cbiAgICA8L2xpPlxuICAgIDxsaSBjbGFzczppcy1hY3RpdmU9e3BhZ2VTZWxlY3RlZCA9PT0gNX0+XG4gICAgICA8YSBvbjpjbGljaz17KGUpID0+IChwYWdlU2VsZWN0ZWQgPSA1KX0+LTwvYT5cbiAgICA8L2xpPlxuICA8L3VsPlxuPC9kaXY+XG5cbjxkaXY+XG5cbiAgeyNpZiBwYWdlU2VsZWN0ZWQgPT0gMX1cbiAgICA8VGFibGVcbiAgICAgIHVybD1cIi9wZ2FwaS9ldmVudHMvdmlld19vcGVuX2V2ZW50c1wiXG4gICAgICBwYXJhbXM9e3BhcmFtc01vbml0b3J9XG4gICAgICBjb2x1bW5zPXtDb2x1bW5zTW9uaXRvcn0gLz5cbiAgezplbHNlIGlmIHBhZ2VTZWxlY3RlZCA9PSAyfVxuICAgIDxUYWJsZVxuICAgICAgdXJsPVwiL3BnYXBpL2V4dGVybmFsX2RhdGEvZG9jdW1lbnRvc194bWxfcmVzdW1lbl9ob3lcIlxuICAgICAgcGFyYW1zPXtwYXJhbXNkb2N1bWVudG9zX3Bvcl9jb25zdWx0YXJfZXN0YWRvfVxuICAgICAgY29sdW1ucz17Q29sdW1zRG9jc1Jlc3VtZW5Ib3l9IC8+XG4gIHs6ZWxzZSBpZiBwYWdlU2VsZWN0ZWQgPT0gM31cbiAgICA8VGFibGVcbiAgICAgIHVybD1cIi9wZ2FwaS9ldGFybS9kb2N1bWVudG9zX3Bvcl9jb25zdWx0YXJfZXN0YWRvXCJcbiAgICAgIHBhcmFtcz17cGFyYW1zZG9jdW1lbnRvc19wb3JfY29uc3VsdGFyX2VzdGFkb31cbiAgICAgIGNvbHVtbnM9e0NvbHVtbnNkb2N1bWVudG9zX3Bvcl9jb25zdWx0YXJfZXN0YWRvfSAvPlxuICB7OmVsc2UgaWYgcGFnZVNlbGVjdGVkID09IDR9XG4gICAgPHNlY3Rpb24gY2xhc3M9XCJ0YWItY29udGVudFwiPlxuICAgICAgPFRhYmxlXG4gICAgICAgIHVybD1cIi9wZ2FwaS9ldGFybS9tb3ZpbnZfcGVuZGllbnRlc19jYXJnYXJcIlxuICAgICAgICBwYXJhbXM9e3BhcmFtc2RvY3VtZW50b3NfcG9yX2NvbnN1bHRhcl9lc3RhZG99XG4gICAgICAgIGNvbHVtbnM9e0NPTFVNTlNfbW92aW52X3BlbmRpZW50ZXNfY2FyZ2FyfSAvPlxuICAgIDwvc2VjdGlvbj5cbiAgezplbHNlfVxuICAgIDxzZWN0aW9uIGNsYXNzPVwidGFiLWNvbnRlbnRcIj5ObyBpbXBsZW1lbnRhZG88L3NlY3Rpb24+XG4gIHsvaWZ9XG5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWtGRSxXQUFXLGNBQUMsQ0FBQyxBQUNYLGFBQWEsQ0FBRSxLQUFLLEFBQ3RCLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

// (96:2) <span slot="Title">
function create_Title_slot(ctx) {
	let span;
	let i;
	let t;

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    OPEN MONITORING SYSTEM");
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { slot: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "I", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "\n    OPEN MONITORING SYSTEM");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-shield-alt");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 96, 4, 2857);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "slot", "Title");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 95, 2, 2833);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_Title_slot.name,
		type: "slot",
		source: "(96:2) <span slot=\\\"Title\\\">",
		ctx
	});

	return block;
}

// (152:2) {:else}
function create_else_block(ctx) {
	let section;
	let t;

	const block = {
		c: function create() {
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("No implementado");
			this.h();
		},
		l: function claim(nodes) {
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(section_nodes, "No implementado");
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "tab-content");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 152, 4, 4536);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, t);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(152:2) {:else}",
		ctx
	});

	return block;
}

// (145:30) 
function create_if_block_3(ctx) {
	let section;
	let table;
	let current;

	table = new _components_Table_Table_svelte__WEBPACK_IMPORTED_MODULE_4__["default"]({
			props: {
				url: "/pgapi/etarm/movinv_pendientes_cargar",
				params: /*paramsdocumentos_por_consultar_estado*/ ctx[3],
				columns: /*COLUMNS_movinv_pendientes_cargar*/ ctx[7]
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(table.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(table.$$.fragment, section_nodes);
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "tab-content");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 145, 4, 4303);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(table, section, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			const table_changes = {};
			if (dirty & /*paramsdocumentos_por_consultar_estado*/ 8) table_changes.params = /*paramsdocumentos_por_consultar_estado*/ ctx[3];
			table.$set(table_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(table.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(table.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(table);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_3.name,
		type: "if",
		source: "(145:30) ",
		ctx
	});

	return block;
}

// (140:30) 
function create_if_block_2(ctx) {
	let table;
	let current;

	table = new _components_Table_Table_svelte__WEBPACK_IMPORTED_MODULE_4__["default"]({
			props: {
				url: "/pgapi/etarm/documentos_por_consultar_estado",
				params: /*paramsdocumentos_por_consultar_estado*/ ctx[3],
				columns: /*Columnsdocumentos_por_consultar_estado*/ ctx[5]
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(table.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(table.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(table, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const table_changes = {};
			if (dirty & /*paramsdocumentos_por_consultar_estado*/ 8) table_changes.params = /*paramsdocumentos_por_consultar_estado*/ ctx[3];
			table.$set(table_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(table.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(table.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(table, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_2.name,
		type: "if",
		source: "(140:30) ",
		ctx
	});

	return block;
}

// (135:30) 
function create_if_block_1(ctx) {
	let table;
	let current;

	table = new _components_Table_Table_svelte__WEBPACK_IMPORTED_MODULE_4__["default"]({
			props: {
				url: "/pgapi/external_data/documentos_xml_resumen_hoy",
				params: /*paramsdocumentos_por_consultar_estado*/ ctx[3],
				columns: /*ColumsDocsResumenHoy*/ ctx[6]
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(table.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(table.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(table, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const table_changes = {};
			if (dirty & /*paramsdocumentos_por_consultar_estado*/ 8) table_changes.params = /*paramsdocumentos_por_consultar_estado*/ ctx[3];
			table.$set(table_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(table.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(table.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(table, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(135:30) ",
		ctx
	});

	return block;
}

// (130:2) {#if pageSelected == 1}
function create_if_block(ctx) {
	let table;
	let current;

	table = new _components_Table_Table_svelte__WEBPACK_IMPORTED_MODULE_4__["default"]({
			props: {
				url: "/pgapi/events/view_open_events",
				params: /*paramsMonitor*/ ctx[2],
				columns: /*ColumnsMonitor*/ ctx[4]
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(table.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(table.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(table, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const table_changes = {};
			if (dirty & /*paramsMonitor*/ 4) table_changes.params = /*paramsMonitor*/ ctx[2];
			table.$set(table_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(table.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(table.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(table, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(130:2) {#if pageSelected == 1}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let menu;
	let t0;
	let div0;
	let ul;
	let li0;
	let a0;
	let t1;
	let t2;
	let li1;
	let a1;
	let t3;
	let t4;
	let li2;
	let a2;
	let t5;
	let t6;
	let li3;
	let a3;
	let t7;
	let t8;
	let li4;
	let a4;
	let t9;
	let t10;
	let div1;
	let current_block_type_index;
	let if_block;
	let current;
	let mounted;
	let dispose;

	menu = new _components_Menu_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({
			props: {
				segment: /*segment*/ ctx[0],
				$$slots: { Title: [create_Title_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	const if_block_creators = [
		create_if_block,
		create_if_block_1,
		create_if_block_2,
		create_if_block_3,
		create_else_block
	];

	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (/*pageSelected*/ ctx[1] == 1) return 0;
		if (/*pageSelected*/ ctx[1] == 2) return 1;
		if (/*pageSelected*/ ctx[1] == 3) return 2;
		if (/*pageSelected*/ ctx[1] == 4) return 3;
		return 4;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(menu.$$.fragment);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Eventos");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Fact. Electrónica - Resumen Hoy");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Fact. Electrónica - Documentos Pendientes");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Mov. Inv. Pendientes");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			a4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("-");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if_block.c();
			this.h();
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(menu.$$.fragment, nodes);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "UL", {});
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li0);
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li0_nodes, "A", {});
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "Eventos");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li1);
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li1_nodes, "A", {});
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "Fact. Electrónica - Resumen Hoy");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li2);
			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li2_nodes, "A", {});
			var a2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a2);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a2_nodes, "Fact. Electrónica - Documentos Pendientes");
			a2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li3);
			a3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li3_nodes, "A", {});
			var a3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a3);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a3_nodes, "Mov. Inv. Pendientes");
			a3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {});
			var li4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li4);
			a4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "A", {});
			var a4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a4);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a4_nodes, "-");
			a4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {});
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			if_block.l(div1_nodes);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 106, 6, 3082);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li0, "is-active", /*pageSelected*/ ctx[1] === 1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li0, file, 105, 4, 3034);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 109, 6, 3196);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li1, "is-active", /*pageSelected*/ ctx[1] === 2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li1, file, 108, 4, 3148);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a2, file, 114, 6, 3350);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li2, "is-active", /*pageSelected*/ ctx[1] === 3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li2, file, 113, 4, 3302);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a3, file, 119, 6, 3514);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li3, "is-active", /*pageSelected*/ ctx[1] === 4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li3, file, 118, 4, 3466);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a4, file, 122, 6, 3641);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li4, "is-active", /*pageSelected*/ ctx[1] === 5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li4, file, 121, 4, 3593);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 104, 2, 3025);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "tabs is-small tab_margin svelte-hrxrjf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 102, 0, 2936);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 127, 0, 3713);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(menu, target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li0, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li1, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, a2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a2, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, a3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a3, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li4, a4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a4, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t10, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div1, anchor);
			if_blocks[current_block_type_index].m(div1, null);
			current = true;

			if (!mounted) {
				dispose = [
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(a0, "click", /*click_handler*/ ctx[8], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(a1, "click", /*click_handler_1*/ ctx[9], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(a2, "click", /*click_handler_2*/ ctx[10], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(a3, "click", /*click_handler_3*/ ctx[11], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(a4, "click", /*click_handler_4*/ ctx[12], false, false, false)
				];

				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			const menu_changes = {};
			if (dirty & /*segment*/ 1) menu_changes.segment = /*segment*/ ctx[0];

			if (dirty & /*$$scope*/ 32768) {
				menu_changes.$$scope = { dirty, ctx };
			}

			menu.$set(menu_changes);

			if (dirty & /*pageSelected*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li0, "is-active", /*pageSelected*/ ctx[1] === 1);
			}

			if (dirty & /*pageSelected*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li1, "is-active", /*pageSelected*/ ctx[1] === 2);
			}

			if (dirty & /*pageSelected*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li2, "is-active", /*pageSelected*/ ctx[1] === 3);
			}

			if (dirty & /*pageSelected*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li3, "is-active", /*pageSelected*/ ctx[1] === 4);
			}

			if (dirty & /*pageSelected*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(li4, "is-active", /*pageSelected*/ ctx[1] === 5);
			}

			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index === previous_block_index) {
				if_blocks[current_block_type_index].p(ctx, dirty);
			} else {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block = if_blocks[current_block_type_index];

				if (!if_block) {
					if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
				if_block.m(div1, null);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(menu.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(menu.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(menu, detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t10);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div1);
			if_blocks[current_block_type_index].d();
			mounted = false;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function ClickVehicleSelected(id) {
	console.log(id);
	window.location.href = "/home";
}

function instance($$self, $$props, $$invalidate) {
	let { segment } = $$props;
	let FData = new _components_FetchData_js__WEBPACK_IMPORTED_MODULE_5__["FetchData"]();
	let pageSelected = 0;
	let paramsMonitor = { iddivision: -1 };

	let ColumnsMonitor = {
		idevent: { label: "ID" },
		dateevent: { label: "Fecha", type: "Date" },
		account_name: { label: "Tienda" },
		label_status: { label: "Estado" },
		priority: { label: "P", type: "Priority" },
		label_eventtype: { label: "Evento" },
		description: { label: "Descripción" }
	};

	let paramsdocumentos_por_consultar_estado = { iddivision: -1 };

	let Columnsdocumentos_por_consultar_estado = {
		fecha_emision: { label: "Emisiónx", type: "Date" },
		account_name: { label: "Tienda" },
		serie_documento: { label: "Documento" },
		identification: { label: "Cod. SAP" },
		tipo_documento: { label: "Tipo" },
		matriz: { label: "Matriz", type: "Boolean-Color" },
		enviado: { label: "Enviado", type: "Boolean-Color" },
		autorizado: {
			label: "Autorizado",
			type: "Boolean-Color"
		},
		car: { label: "Car", type: "Boolean-Color" }
	};

	//account_name, account, identification, en_pv, en_matriz, enviados , autorizados, en_car
	let ColumsDocsResumenHoy = {
		account_name: { label: "Tienda" },
		identification: { label: "Cod. SAP" },
		en_pv: { label: "PV" },
		en_matriz: { label: "Matriz" },
		enviados: { label: "Enviados" },
		autorizados: { label: "Autorizados" },
		en_car: { label: "Car" }
	};

	let COLUMNS_movinv_pendientes_cargar = {
		account_name: { label: "Tienda" },
		//account: { hidden: true },
		bukrs: { label: "bukrs" },
		bwart: { label: "bwart" },
		//cpudt: { hidden: true },
		//cputm: { hidden: true },
		shkzg: { label: "shkzg" },
		matnr: { label: "matnr" },
		mblnr: { label: "mblnr" },
		menge: { label: "menge" },
		werks: { label: "werks" },
		datetimefile: { label: "Fecha", type: "Date" }
	};

	//console.log(ColumnsMonitor);
	function ChangePage(pageId) {
		$$invalidate(1, pageSelected = pageId);
		console.log(pageSelected);
	}

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		$$invalidate(2, paramsMonitor.iddivision = Object(_components_UrlSearch_js__WEBPACK_IMPORTED_MODULE_6__["UrlSearch"])("iddivision"), paramsMonitor);
		$$invalidate(3, paramsdocumentos_por_consultar_estado.iddivision = paramsMonitor.iddivision, paramsdocumentos_por_consultar_estado);

		//console.log(paramsMonitor);
		$$invalidate(1, pageSelected = 1);
	});

	const writable_props = ["segment"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<Monitor> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Monitor", $$slots, []);
	const click_handler = e => $$invalidate(1, pageSelected = 1);
	const click_handler_1 = e => $$invalidate(1, pageSelected = 2);
	const click_handler_2 = e => $$invalidate(1, pageSelected = 3);
	const click_handler_3 = e => $$invalidate(1, pageSelected = 4);
	const click_handler_4 = e => $$invalidate(1, pageSelected = 5);

	$$self.$set = $$props => {
		if ("segment" in $$props) $$invalidate(0, segment = $$props.segment);
	};

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		Menu: _components_Menu_svelte__WEBPACK_IMPORTED_MODULE_2__["default"],
		Monitor: _components_Monitor_svelte__WEBPACK_IMPORTED_MODULE_3__["default"],
		Table: _components_Table_Table_svelte__WEBPACK_IMPORTED_MODULE_4__["default"],
		FetchData: _components_FetchData_js__WEBPACK_IMPORTED_MODULE_5__["FetchData"],
		UrlSearch: _components_UrlSearch_js__WEBPACK_IMPORTED_MODULE_6__["UrlSearch"],
		segment,
		FData,
		pageSelected,
		paramsMonitor,
		ColumnsMonitor,
		paramsdocumentos_por_consultar_estado,
		Columnsdocumentos_por_consultar_estado,
		ColumsDocsResumenHoy,
		COLUMNS_movinv_pendientes_cargar,
		ChangePage,
		ClickVehicleSelected
	});

	$$self.$inject_state = $$props => {
		if ("segment" in $$props) $$invalidate(0, segment = $$props.segment);
		if ("FData" in $$props) FData = $$props.FData;
		if ("pageSelected" in $$props) $$invalidate(1, pageSelected = $$props.pageSelected);
		if ("paramsMonitor" in $$props) $$invalidate(2, paramsMonitor = $$props.paramsMonitor);
		if ("ColumnsMonitor" in $$props) $$invalidate(4, ColumnsMonitor = $$props.ColumnsMonitor);
		if ("paramsdocumentos_por_consultar_estado" in $$props) $$invalidate(3, paramsdocumentos_por_consultar_estado = $$props.paramsdocumentos_por_consultar_estado);
		if ("Columnsdocumentos_por_consultar_estado" in $$props) $$invalidate(5, Columnsdocumentos_por_consultar_estado = $$props.Columnsdocumentos_por_consultar_estado);
		if ("ColumsDocsResumenHoy" in $$props) $$invalidate(6, ColumsDocsResumenHoy = $$props.ColumsDocsResumenHoy);
		if ("COLUMNS_movinv_pendientes_cargar" in $$props) $$invalidate(7, COLUMNS_movinv_pendientes_cargar = $$props.COLUMNS_movinv_pendientes_cargar);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [
		segment,
		pageSelected,
		paramsMonitor,
		paramsdocumentos_por_consultar_estado,
		ColumnsMonitor,
		Columnsdocumentos_por_consultar_estado,
		ColumsDocsResumenHoy,
		COLUMNS_movinv_pendientes_cargar,
		click_handler,
		click_handler_1,
		click_handler_2,
		click_handler_3,
		click_handler_4
	];
}

class Monitor_1 extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-hrxrjf-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { segment: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Monitor_1",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*segment*/ ctx[0] === undefined && !("segment" in props)) {
			console_1.warn("<Monitor> was created without expected prop 'segment'");
		}
	}

	get segment() {
		throw new Error("<Monitor>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set segment(value) {
		throw new Error("<Monitor>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Monitor_1);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8uL3NyYy9yb3V0ZXMvbW9uaXRvci9pbmRleC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUNtQztBQUNlO0FBQ007QUFDRTtBQUNFO0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NEQThJNUMsR0FBcUM7a0RBQ3BDLEdBQWdDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2SEFEakMsR0FBcUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0RBTnZDLEdBQXFDO3dEQUNwQyxHQUFzQzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZIQUR2QyxHQUFxQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NEQUxyQyxHQUFxQztzQ0FDcEMsR0FBb0I7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2SEFEckIsR0FBcUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs4QkFMckMsR0FBYTtnQ0FDWixHQUFjOzs7Ozs7Ozs7Ozs7Ozs7Ozs7NkVBRGYsR0FBYTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dUJBSHBCLEdBQVksT0FBSSxDQUFDO3VCQUtaLEdBQVksT0FBSSxDQUFDO3VCQUtqQixHQUFZLE9BQUksQ0FBQzt1QkFLakIsR0FBWSxPQUFJLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MkdBdkNKLEdBQVksUUFBSyxDQUFDOzs7MkdBR2xCLEdBQVksUUFBSyxDQUFDOzs7MkdBS2xCLEdBQVksUUFBSyxDQUFDOzs7MkdBS2xCLEdBQVksUUFBSyxDQUFDOzs7MkdBR2xCLEdBQVksUUFBSyxDQUFDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0R0FoQmxCLEdBQVksUUFBSyxDQUFDOzs7OzRHQUdsQixHQUFZLFFBQUssQ0FBQzs7Ozs0R0FLbEIsR0FBWSxRQUFLLENBQUM7Ozs7NEdBS2xCLEdBQVksUUFBSyxDQUFDOzs7OzRHQUdsQixHQUFZLFFBQUssQ0FBQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztTQXJEaEMsb0JBQW9CLENBQUMsRUFBRTtDQUM5QixPQUFPLENBQUMsR0FBRyxDQUFDLEVBQUU7Q0FDZCxNQUFNLENBQUMsUUFBUSxDQUFDLElBQUksR0FBRyxPQUFPOzs7O09BOURyQixPQUFPO0tBRWQsS0FBSyxPQUFPLGtFQUFTO0tBQ3JCLFlBQVksR0FBRyxDQUFDO0tBQ2hCLGFBQWEsS0FBSyxVQUFVLEdBQUcsQ0FBQzs7S0FDaEMsY0FBYztFQUNoQixPQUFPLElBQUssS0FBSyxFQUFFLElBQUk7RUFDdkIsU0FBUyxJQUFLLEtBQUssRUFBRSxPQUFPLEVBQUUsSUFBSSxFQUFFLE1BQU07RUFDMUMsWUFBWSxJQUFJLEtBQUssRUFBRSxRQUFRO0VBQy9CLFlBQVksSUFBSSxLQUFLLEVBQUUsUUFBUTtFQUMvQixRQUFRLElBQUksS0FBSyxFQUFFLEdBQUcsRUFBRSxJQUFJLEVBQUUsVUFBVTtFQUN4QyxlQUFlLElBQUksS0FBSyxFQUFFLFFBQVE7RUFDbEMsV0FBVyxJQUFJLEtBQUssRUFBRSxhQUFhOzs7S0FHakMscUNBQXFDLEtBQUssVUFBVSxHQUFHLENBQUM7O0tBQ3hELHNDQUFzQztFQUN4QyxhQUFhLElBQUssS0FBSyxFQUFFLFVBQVUsRUFBRSxJQUFJLEVBQUUsTUFBTTtFQUNqRCxZQUFZLElBQUksS0FBSyxFQUFFLFFBQVE7RUFDL0IsZUFBZSxJQUFJLEtBQUssRUFBRSxXQUFXO0VBQ3JDLGNBQWMsSUFBSSxLQUFLLEVBQUUsVUFBVTtFQUNuQyxjQUFjLElBQUksS0FBSyxFQUFFLE1BQU07RUFDL0IsTUFBTSxJQUFJLEtBQUssRUFBRSxRQUFRLEVBQUUsSUFBSSxFQUFFLGVBQWU7RUFDaEQsT0FBTyxJQUFJLEtBQUssRUFBRSxTQUFTLEVBQUUsSUFBSSxFQUFFLGVBQWU7RUFDbEQsVUFBVTtHQUFJLEtBQUssRUFBRSxZQUFZO0dBQUUsSUFBSSxFQUFFLGVBQWU7O0VBQ3hELEdBQUcsSUFBSSxLQUFLLEVBQUUsS0FBSyxFQUFFLElBQUksRUFBRSxlQUFlOzs7O0tBSXhDLG9CQUFvQjtFQUN0QixZQUFZLElBQUksS0FBSyxFQUFFLFFBQVE7RUFDL0IsY0FBYyxJQUFJLEtBQUssRUFBRSxVQUFVO0VBQ25DLEtBQUssSUFBSSxLQUFLLEVBQUUsSUFBSTtFQUNwQixTQUFTLElBQUksS0FBSyxFQUFFLFFBQVE7RUFDNUIsUUFBUSxJQUFJLEtBQUssRUFBRSxVQUFVO0VBQzdCLFdBQVcsSUFBSSxLQUFLLEVBQUUsYUFBYTtFQUNuQyxNQUFNLElBQUksS0FBSyxFQUFFLEtBQUs7OztLQUdwQixnQ0FBZ0M7RUFDbEMsWUFBWSxJQUFJLEtBQUssRUFBRSxRQUFROztFQUUvQixLQUFLLElBQUksS0FBSyxFQUFFLE9BQU87RUFDdkIsS0FBSyxJQUFJLEtBQUssRUFBRSxPQUFPOzs7RUFHdkIsS0FBSyxJQUFJLEtBQUssRUFBRSxPQUFPO0VBQ3ZCLEtBQUssSUFBSSxLQUFLLEVBQUUsT0FBTztFQUN2QixLQUFLLElBQUksS0FBSyxFQUFFLE9BQU87RUFDdkIsS0FBSyxJQUFJLEtBQUssRUFBRSxPQUFPO0VBQ3ZCLEtBQUssSUFBSSxLQUFLLEVBQUUsT0FBTztFQUN2QixZQUFZLElBQUksS0FBSyxFQUFFLE9BQU8sRUFBRSxJQUFJLEVBQUUsTUFBTTs7OztVQUlyQyxVQUFVLENBQUMsTUFBTTtrQkFDeEIsWUFBWSxHQUFHLE1BQU07RUFDckIsT0FBTyxDQUFDLEdBQUcsQ0FBQyxZQUFZOzs7Q0FRMUIsc0RBQU87a0JBQ0wsYUFBYSxDQUFDLFVBQVUsR0FBRywwRUFBUyxDQUFDLFlBQVk7a0JBQ2pELHFDQUFxQyxDQUFDLFVBQVUsR0FBRyxhQUFhLENBQUMsVUFBVTs7O2tCQUUzRSxZQUFZLEdBQUcsQ0FBQzs7Ozs7Ozs7Ozs7dUJBNkJBLENBQUMsb0JBQU0sWUFBWSxHQUFHLENBQUM7eUJBR3ZCLENBQUMsb0JBQU0sWUFBWSxHQUFHLENBQUM7eUJBS3ZCLENBQUMsb0JBQU0sWUFBWSxHQUFHLENBQUM7eUJBS3ZCLENBQUMsb0JBQU0sWUFBWSxHQUFHLENBQUM7eUJBR3ZCLENBQUMsb0JBQU0sWUFBWSxHQUFHLENBQUMiLCJmaWxlIjoiYzgyNTJmNDQ0MDkzYjA0MjgyYjgvbW9uaXRvci5tb25pdG9yLmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gXCJzdmVsdGVcIjtcbiAgaW1wb3J0IE1lbnUgZnJvbSBcIi4uLy4uL2NvbXBvbmVudHMvTWVudS5zdmVsdGVcIjtcbiAgaW1wb3J0IE1vbml0b3IgZnJvbSBcIi4uLy4uL2NvbXBvbmVudHMvTW9uaXRvci5zdmVsdGVcIjtcbiAgaW1wb3J0IFRhYmxlIGZyb20gXCIuLi8uLi9jb21wb25lbnRzL1RhYmxlL1RhYmxlLnN2ZWx0ZVwiO1xuICBpbXBvcnQgeyBGZXRjaERhdGEgfSBmcm9tIFwiLi4vLi4vY29tcG9uZW50cy9GZXRjaERhdGEuanNcIjtcbiAgaW1wb3J0IHsgVXJsU2VhcmNoIH0gZnJvbSBcIi4uLy4uL2NvbXBvbmVudHMvVXJsU2VhcmNoLmpzXCI7XG5cbiAgZXhwb3J0IGxldCBzZWdtZW50O1xuXG4gIGxldCBGRGF0YSA9IG5ldyBGZXRjaERhdGEoKTtcbiAgbGV0IHBhZ2VTZWxlY3RlZCA9IDA7XG4gIGxldCBwYXJhbXNNb25pdG9yID0geyBpZGRpdmlzaW9uOiAtMSB9O1xuICBsZXQgQ29sdW1uc01vbml0b3IgPSB7XG4gICAgaWRldmVudDogeyAgbGFiZWw6IFwiSURcIiB9LFxuICAgIGRhdGVldmVudDogeyAgbGFiZWw6IFwiRmVjaGFcIiwgdHlwZTogXCJEYXRlXCIgfSxcbiAgICBhY2NvdW50X25hbWU6IHsgbGFiZWw6IFwiVGllbmRhXCIgfSxcbiAgICBsYWJlbF9zdGF0dXM6IHsgbGFiZWw6IFwiRXN0YWRvXCIgfSxcbiAgICBwcmlvcml0eTogeyBsYWJlbDogXCJQXCIsIHR5cGU6IFwiUHJpb3JpdHlcIiB9LFxuICAgIGxhYmVsX2V2ZW50dHlwZTogeyBsYWJlbDogXCJFdmVudG9cIiB9LFxuICAgIGRlc2NyaXB0aW9uOiB7IGxhYmVsOiBcIkRlc2NyaXBjacOzblwiIH0sXG4gIH07XG5cbiAgbGV0IHBhcmFtc2RvY3VtZW50b3NfcG9yX2NvbnN1bHRhcl9lc3RhZG8gPSB7IGlkZGl2aXNpb246IC0xIH07XG4gIGxldCBDb2x1bW5zZG9jdW1lbnRvc19wb3JfY29uc3VsdGFyX2VzdGFkbyA9IHtcbiAgICBmZWNoYV9lbWlzaW9uOiB7ICBsYWJlbDogXCJFbWlzacOzbnhcIiwgdHlwZTogXCJEYXRlXCIgfSxcbiAgICBhY2NvdW50X25hbWU6IHsgbGFiZWw6IFwiVGllbmRhXCIgfSxcbiAgICBzZXJpZV9kb2N1bWVudG86IHsgbGFiZWw6IFwiRG9jdW1lbnRvXCIgfSxcbiAgICBpZGVudGlmaWNhdGlvbjogeyBsYWJlbDogXCJDb2QuIFNBUFwiIH0sXG4gICAgdGlwb19kb2N1bWVudG86IHsgbGFiZWw6IFwiVGlwb1wiIH0sXG4gICAgbWF0cml6OiB7IGxhYmVsOiBcIk1hdHJpelwiLCB0eXBlOiBcIkJvb2xlYW4tQ29sb3JcIiB9LFxuICAgIGVudmlhZG86IHsgbGFiZWw6IFwiRW52aWFkb1wiLCB0eXBlOiBcIkJvb2xlYW4tQ29sb3JcIiB9LFxuICAgIGF1dG9yaXphZG86IHsgbGFiZWw6IFwiQXV0b3JpemFkb1wiLCB0eXBlOiBcIkJvb2xlYW4tQ29sb3JcIiB9LFxuICAgIGNhcjogeyBsYWJlbDogXCJDYXJcIiwgdHlwZTogXCJCb29sZWFuLUNvbG9yXCIgfSxcbiAgfTtcblxuICAvL2FjY291bnRfbmFtZSwgYWNjb3VudCwgaWRlbnRpZmljYXRpb24sIGVuX3B2LCBlbl9tYXRyaXosIGVudmlhZG9zICwgYXV0b3JpemFkb3MsIGVuX2NhclxuICBsZXQgQ29sdW1zRG9jc1Jlc3VtZW5Ib3kgPSB7XG4gICAgYWNjb3VudF9uYW1lOiB7IGxhYmVsOiBcIlRpZW5kYVwiIH0sXG4gICAgaWRlbnRpZmljYXRpb246IHsgbGFiZWw6IFwiQ29kLiBTQVBcIiB9LFxuICAgIGVuX3B2OiB7IGxhYmVsOiBcIlBWXCIgfSxcbiAgICBlbl9tYXRyaXo6IHsgbGFiZWw6IFwiTWF0cml6XCIgfSxcbiAgICBlbnZpYWRvczogeyBsYWJlbDogXCJFbnZpYWRvc1wiIH0sXG4gICAgYXV0b3JpemFkb3M6IHsgbGFiZWw6IFwiQXV0b3JpemFkb3NcIiB9LFxuICAgIGVuX2NhcjogeyBsYWJlbDogXCJDYXJcIiB9LFxuICB9O1xuXG4gIGxldCBDT0xVTU5TX21vdmludl9wZW5kaWVudGVzX2NhcmdhciA9IHtcbiAgICBhY2NvdW50X25hbWU6IHsgbGFiZWw6IFwiVGllbmRhXCIgfSxcbiAgICAvL2FjY291bnQ6IHsgaGlkZGVuOiB0cnVlIH0sXG4gICAgYnVrcnM6IHsgbGFiZWw6IFwiYnVrcnNcIiB9LFxuICAgIGJ3YXJ0OiB7IGxhYmVsOiBcImJ3YXJ0XCIgfSxcbiAgICAvL2NwdWR0OiB7IGhpZGRlbjogdHJ1ZSB9LFxuICAgIC8vY3B1dG06IHsgaGlkZGVuOiB0cnVlIH0sXG4gICAgc2hremc6IHsgbGFiZWw6IFwic2hremdcIiB9LFxuICAgIG1hdG5yOiB7IGxhYmVsOiBcIm1hdG5yXCIgfSxcbiAgICBtYmxucjogeyBsYWJlbDogXCJtYmxuclwiIH0sXG4gICAgbWVuZ2U6IHsgbGFiZWw6IFwibWVuZ2VcIiB9LFxuICAgIHdlcmtzOiB7IGxhYmVsOiBcIndlcmtzXCIgfSxcbiAgICBkYXRldGltZWZpbGU6IHsgbGFiZWw6IFwiRmVjaGFcIiwgdHlwZTogXCJEYXRlXCIgfVxuICB9O1xuXG4gIC8vY29uc29sZS5sb2coQ29sdW1uc01vbml0b3IpO1xuICBmdW5jdGlvbiBDaGFuZ2VQYWdlKHBhZ2VJZCkge1xuICAgIHBhZ2VTZWxlY3RlZCA9IHBhZ2VJZDtcbiAgICBjb25zb2xlLmxvZyhwYWdlU2VsZWN0ZWQpO1xuICB9XG5cbiAgZnVuY3Rpb24gQ2xpY2tWZWhpY2xlU2VsZWN0ZWQoaWQpIHtcbiAgICBjb25zb2xlLmxvZyhpZCk7XG4gICAgd2luZG93LmxvY2F0aW9uLmhyZWYgPSBcIi9ob21lXCI7XG4gIH1cblxuICBvbk1vdW50KGFzeW5jICgpID0+IHtcbiAgICBwYXJhbXNNb25pdG9yLmlkZGl2aXNpb24gPSBVcmxTZWFyY2goXCJpZGRpdmlzaW9uXCIpO1xuICAgIHBhcmFtc2RvY3VtZW50b3NfcG9yX2NvbnN1bHRhcl9lc3RhZG8uaWRkaXZpc2lvbiA9IHBhcmFtc01vbml0b3IuaWRkaXZpc2lvbjtcbiAgICAvL2NvbnNvbGUubG9nKHBhcmFtc01vbml0b3IpO1xuICAgIHBhZ2VTZWxlY3RlZCA9IDE7XG4gIH0pO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgLnRhYl9tYXJnaW4ge1xuICAgIG1hcmdpbi1ib3R0b206IDAuNWVtO1xuICB9XG4gIC8qICAuaWNvbl9saW5rIGEge1xuICAgIGNvbG9yOiB3aGl0ZTtcbiAgfVxuXG4gIC5pY29uX2xpbmsgYTpob3ZlciB7XG4gICAgY29sb3I6IHJnYigyNTUsIDEwMiwgMCk7XG4gIH0qL1xuPC9zdHlsZT5cblxuPE1lbnUge3NlZ21lbnR9PlxuICA8c3BhbiBzbG90PVwiVGl0bGVcIj5cbiAgICA8aSBjbGFzcz1cImZhcyBmYS1zaGllbGQtYWx0XCIgLz5cbiAgICBPUEVOIE1PTklUT1JJTkcgU1lTVEVNXG4gIDwvc3Bhbj5cblxuPC9NZW51PlxuXG48ZGl2IGNsYXNzPVwidGFicyBpcy1zbWFsbCB0YWJfbWFyZ2luXCI+XG4gIDwhLS0gc3ZlbHRlLWlnbm9yZSBhMTF5LW1pc3NpbmctYXR0cmlidXRlIC0tPlxuICA8dWw+XG4gICAgPGxpIGNsYXNzOmlzLWFjdGl2ZT17cGFnZVNlbGVjdGVkID09PSAxfT5cbiAgICAgIDxhIG9uOmNsaWNrPXsoZSkgPT4gKHBhZ2VTZWxlY3RlZCA9IDEpfT5FdmVudG9zPC9hPlxuICAgIDwvbGk+XG4gICAgPGxpIGNsYXNzOmlzLWFjdGl2ZT17cGFnZVNlbGVjdGVkID09PSAyfT5cbiAgICAgIDxhIG9uOmNsaWNrPXsoZSkgPT4gKHBhZ2VTZWxlY3RlZCA9IDIpfT5cbiAgICAgICAgRmFjdC4gRWxlY3Ryw7NuaWNhIC0gUmVzdW1lbiBIb3lcbiAgICAgIDwvYT5cbiAgICA8L2xpPlxuICAgIDxsaSBjbGFzczppcy1hY3RpdmU9e3BhZ2VTZWxlY3RlZCA9PT0gM30+XG4gICAgICA8YSBvbjpjbGljaz17KGUpID0+IChwYWdlU2VsZWN0ZWQgPSAzKX0+XG4gICAgICAgIEZhY3QuIEVsZWN0csOzbmljYSAtIERvY3VtZW50b3MgUGVuZGllbnRlc1xuICAgICAgPC9hPlxuICAgIDwvbGk+XG4gICAgPGxpIGNsYXNzOmlzLWFjdGl2ZT17cGFnZVNlbGVjdGVkID09PSA0fT5cbiAgICAgIDxhIG9uOmNsaWNrPXsoZSkgPT4gKHBhZ2VTZWxlY3RlZCA9IDQpfT5Nb3YuIEludi4gUGVuZGllbnRlczwvYT5cbiAgICA8L2xpPlxuICAgIDxsaSBjbGFzczppcy1hY3RpdmU9e3BhZ2VTZWxlY3RlZCA9PT0gNX0+XG4gICAgICA8YSBvbjpjbGljaz17KGUpID0+IChwYWdlU2VsZWN0ZWQgPSA1KX0+LTwvYT5cbiAgICA8L2xpPlxuICA8L3VsPlxuPC9kaXY+XG5cbjxkaXY+XG5cbiAgeyNpZiBwYWdlU2VsZWN0ZWQgPT0gMX1cbiAgICA8VGFibGVcbiAgICAgIHVybD1cIi9wZ2FwaS9ldmVudHMvdmlld19vcGVuX2V2ZW50c1wiXG4gICAgICBwYXJhbXM9e3BhcmFtc01vbml0b3J9XG4gICAgICBjb2x1bW5zPXtDb2x1bW5zTW9uaXRvcn0gLz5cbiAgezplbHNlIGlmIHBhZ2VTZWxlY3RlZCA9PSAyfVxuICAgIDxUYWJsZVxuICAgICAgdXJsPVwiL3BnYXBpL2V4dGVybmFsX2RhdGEvZG9jdW1lbnRvc194bWxfcmVzdW1lbl9ob3lcIlxuICAgICAgcGFyYW1zPXtwYXJhbXNkb2N1bWVudG9zX3Bvcl9jb25zdWx0YXJfZXN0YWRvfVxuICAgICAgY29sdW1ucz17Q29sdW1zRG9jc1Jlc3VtZW5Ib3l9IC8+XG4gIHs6ZWxzZSBpZiBwYWdlU2VsZWN0ZWQgPT0gM31cbiAgICA8VGFibGVcbiAgICAgIHVybD1cIi9wZ2FwaS9ldGFybS9kb2N1bWVudG9zX3Bvcl9jb25zdWx0YXJfZXN0YWRvXCJcbiAgICAgIHBhcmFtcz17cGFyYW1zZG9jdW1lbnRvc19wb3JfY29uc3VsdGFyX2VzdGFkb31cbiAgICAgIGNvbHVtbnM9e0NvbHVtbnNkb2N1bWVudG9zX3Bvcl9jb25zdWx0YXJfZXN0YWRvfSAvPlxuICB7OmVsc2UgaWYgcGFnZVNlbGVjdGVkID09IDR9XG4gICAgPHNlY3Rpb24gY2xhc3M9XCJ0YWItY29udGVudFwiPlxuICAgICAgPFRhYmxlXG4gICAgICAgIHVybD1cIi9wZ2FwaS9ldGFybS9tb3ZpbnZfcGVuZGllbnRlc19jYXJnYXJcIlxuICAgICAgICBwYXJhbXM9e3BhcmFtc2RvY3VtZW50b3NfcG9yX2NvbnN1bHRhcl9lc3RhZG99XG4gICAgICAgIGNvbHVtbnM9e0NPTFVNTlNfbW92aW52X3BlbmRpZW50ZXNfY2FyZ2FyfSAvPlxuICAgIDwvc2VjdGlvbj5cbiAgezplbHNlfVxuICAgIDxzZWN0aW9uIGNsYXNzPVwidGFiLWNvbnRlbnRcIj5ObyBpbXBsZW1lbnRhZG88L3NlY3Rpb24+XG4gIHsvaWZ9XG5cbjwvZGl2PlxuIl0sInNvdXJjZVJvb3QiOiIifQ==