<?php  
$GLOBALS["dbmap_open_ams"] = array();
$GLOBALS["dbmap_open_ams"]["account_contacts"]["appointment"] = array("data_type"=>"text", "label"=>"Cargo");
$GLOBALS["dbmap_open_ams"]["account_contacts"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["account_contacts"]["idaccountuser"] = array("data_type"=>"bigint", "label"=>"idaccountuser");
$GLOBALS["dbmap_open_ams"]["account_contacts"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["account_contacts"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["account_contacts"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["account_contacts"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["accounts"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["accounts"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["accounts"]["address_ref"] = array("data_type"=>"text", "label"=>"Referencia Dirección");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_end"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_end");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_failed_access_attempts"] = array("data_type"=>"smallint", "label"=>"admin_failed_access_attempts");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_ip"] = array("data_type"=>"text", "label"=>"admin_ip");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_level"] = array("data_type"=>"integer", "label"=>"admin_level");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_locked_date"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_locked_date");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_pwd"] = array("data_type"=>"text", "label"=>"admin_pwd");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_sessionid"] = array("data_type"=>"text", "label"=>"admin_sessionid");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_start"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_start");
$GLOBALS["dbmap_open_ams"]["accounts"]["admin_username"] = array("data_type"=>"text", "label"=>"admin_username");
$GLOBALS["dbmap_open_ams"]["accounts"]["birthday"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Nacimiento");
$GLOBALS["dbmap_open_ams"]["accounts"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["accounts"]["end_date"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha de finalización");
$GLOBALS["dbmap_open_ams"]["accounts"]["first_name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["accounts"]["gender"] = array("data_type"=>"integer", "label"=>"Género");
$GLOBALS["dbmap_open_ams"]["accounts"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["accounts"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["accounts"]["groups"] = array("data_type"=>"ARRAY", "label"=>"Grupos");
$GLOBALS["dbmap_open_ams"]["accounts"]["idaccountstate"] = array("data_type"=>"integer", "label"=>"Estado de la cuenta");
$GLOBALS["dbmap_open_ams"]["accounts"]["idaccounttype"] = array("data_type"=>"integer", "label"=>"Tipo de cuenta");
$GLOBALS["dbmap_open_ams"]["accounts"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["accounts"]["iddivision"] = array("data_type"=>"integer", "label"=>"iddivision");
$GLOBALS["dbmap_open_ams"]["accounts"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["accounts"]["ididtype"] = array("data_type"=>"integer", "label"=>"Tipo de Identificación");
$GLOBALS["dbmap_open_ams"]["accounts"]["is_admin"] = array("data_type"=>"boolean", "label"=>"is_admin");
$GLOBALS["dbmap_open_ams"]["accounts"]["last_name"] = array("data_type"=>"text", "label"=>"Apellido");
$GLOBALS["dbmap_open_ams"]["accounts"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["accounts"]["postal_code"] = array("data_type"=>"text", "label"=>"Código Postal");
$GLOBALS["dbmap_open_ams"]["accounts"]["start_date"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha de inicio");
$GLOBALS["dbmap_open_ams"]["accounts"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["account_states"]["idaccountstate"] = array("data_type"=>"bigint", "label"=>"idaccountstate");
$GLOBALS["dbmap_open_ams"]["account_states"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["account_states"]["state"] = array("data_type"=>"text", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["account_states"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["account_technicals"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["account_technicals"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["account_technicals"]["idtechnical"] = array("data_type"=>"integer", "label"=>"idtechnical");
$GLOBALS["dbmap_open_ams"]["account_technicals"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["account_types"]["idaccounttype"] = array("data_type"=>"bigint", "label"=>"idaccounttype");
$GLOBALS["dbmap_open_ams"]["account_types"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["account_types"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["account_types"]["type"] = array("data_type"=>"text", "label"=>"Tipo");
$GLOBALS["dbmap_open_ams"]["account_users"]["account_pwd"] = array("data_type"=>"text", "label"=>"account_pwd");
$GLOBALS["dbmap_open_ams"]["account_users"]["account_user"] = array("data_type"=>"text", "label"=>"account_user");
$GLOBALS["dbmap_open_ams"]["account_users"]["appointment"] = array("data_type"=>"text", "label"=>"Cargo");
$GLOBALS["dbmap_open_ams"]["account_users"]["date_end"] = array("data_type"=>"timestamp without time zone", "label"=>"date_end");
$GLOBALS["dbmap_open_ams"]["account_users"]["date_start"] = array("data_type"=>"timestamp without time zone", "label"=>"date_start");
$GLOBALS["dbmap_open_ams"]["account_users"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["account_users"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["account_users"]["idaccountuser"] = array("data_type"=>"bigint", "label"=>"idaccountuser");
$GLOBALS["dbmap_open_ams"]["account_users"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["account_users"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["account_users"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["account_users"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["account_users"]["user"] = array("data_type"=>"integer", "label"=>"Usuario");
$GLOBALS["dbmap_open_ams"]["admin_notifications"]["idadmin_notification"] = array("data_type"=>"bigint", "label"=>"idadmin_notification");
$GLOBALS["dbmap_open_ams"]["admin_notifications"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["attachments"]["file"] = array("data_type"=>"text", "label"=>"Archivo");
$GLOBALS["dbmap_open_ams"]["attachments"]["idattachment"] = array("data_type"=>"bigint", "label"=>"idattachment");
$GLOBALS["dbmap_open_ams"]["attachments"]["md5"] = array("data_type"=>"text", "label"=>"md5");
$GLOBALS["dbmap_open_ams"]["attachments"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["contacts"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["contacts"]["address_ref"] = array("data_type"=>"text", "label"=>"Dirección referencia");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_end"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_end");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_failed_access_attempts"] = array("data_type"=>"smallint", "label"=>"admin_failed_access_attempts");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_ip"] = array("data_type"=>"text", "label"=>"admin_ip");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_level"] = array("data_type"=>"integer", "label"=>"admin_level");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_locked_date"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_locked_date");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_pwd"] = array("data_type"=>"text", "label"=>"admin_pwd");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_sessionid"] = array("data_type"=>"text", "label"=>"admin_sessionid");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_start"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_start");
$GLOBALS["dbmap_open_ams"]["contacts"]["admin_username"] = array("data_type"=>"text", "label"=>"admin_username");
$GLOBALS["dbmap_open_ams"]["contacts"]["birthday"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha nacimiento");
$GLOBALS["dbmap_open_ams"]["contacts"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["contacts"]["first_name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["contacts"]["gender"] = array("data_type"=>"integer", "label"=>"Género");
$GLOBALS["dbmap_open_ams"]["contacts"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["contacts"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["contacts"]["groups"] = array("data_type"=>"ARRAY", "label"=>"Grupos");
$GLOBALS["dbmap_open_ams"]["contacts"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["contacts"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["contacts"]["ididtype"] = array("data_type"=>"integer", "label"=>"Tipo de Identificación");
$GLOBALS["dbmap_open_ams"]["contacts"]["is_admin"] = array("data_type"=>"boolean", "label"=>"is_admin");
$GLOBALS["dbmap_open_ams"]["contacts"]["last_name"] = array("data_type"=>"text", "label"=>"Apellido");
$GLOBALS["dbmap_open_ams"]["contacts"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["contacts"]["postal_code"] = array("data_type"=>"text", "label"=>"Código postal");
$GLOBALS["dbmap_open_ams"]["contacts"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["contacts_groups"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["contacts_groups"]["idcontactgroup"] = array("data_type"=>"bigint", "label"=>"idcontactgroup");
$GLOBALS["dbmap_open_ams"]["contacts_groups"]["idgroup"] = array("data_type"=>"integer", "label"=>"idgroup");
$GLOBALS["dbmap_open_ams"]["contacts_groups"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["division"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["division"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["division"]["iddivision"] = array("data_type"=>"bigint", "label"=>"Empresa");
$GLOBALS["dbmap_open_ams"]["division"]["name"] = array("data_type"=>"text", "label"=>"Empresa");
$GLOBALS["dbmap_open_ams"]["division"]["notes"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["divisions"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["divisions"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["divisions"]["iddivision"] = array("data_type"=>"bigint", "label"=>"Empresa");
$GLOBALS["dbmap_open_ams"]["divisions"]["name"] = array("data_type"=>"text", "label"=>"Empresa");
$GLOBALS["dbmap_open_ams"]["divisions"]["notes"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["emails"]["email"] = array("data_type"=>"text", "label"=>"Email");
$GLOBALS["dbmap_open_ams"]["emails"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["emails"]["idemail"] = array("data_type"=>"bigint", "label"=>"idemail");
$GLOBALS["dbmap_open_ams"]["emails"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["emails"]["notify_if_administrator"] = array("data_type"=>"boolean", "label"=>"notify_if_administrator");
$GLOBALS["dbmap_open_ams"]["emails"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["emails"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["equipments"]["agreement_code_provider"] = array("data_type"=>"text", "label"=>"agreement_code_provider");
$GLOBALS["dbmap_open_ams"]["equipments"]["code_ref"] = array("data_type"=>"text", "label"=>"Código Ref.");
$GLOBALS["dbmap_open_ams"]["equipments"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["equipments"]["equipment"] = array("data_type"=>"text", "label"=>"Equipo");
$GLOBALS["dbmap_open_ams"]["equipments"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["equipments"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["equipments"]["idprovider"] = array("data_type"=>"integer", "label"=>"idprovider");
$GLOBALS["dbmap_open_ams"]["equipments"]["installation_date"] = array("data_type"=>"timestamp without time zone", "label"=>"installation_date");
$GLOBALS["dbmap_open_ams"]["equipments"]["mark"] = array("data_type"=>"text", "label"=>"Marca");
$GLOBALS["dbmap_open_ams"]["equipments"]["model"] = array("data_type"=>"text", "label"=>"Modelo");
$GLOBALS["dbmap_open_ams"]["equipments"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["equipments"]["operability"] = array("data_type"=>"smallint", "label"=>"Operatividad");
$GLOBALS["dbmap_open_ams"]["equipments"]["serial_number"] = array("data_type"=>"text", "label"=>"Numero serie");
$GLOBALS["dbmap_open_ams"]["equipments"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["equipments"]["uninstall_date"] = array("data_type"=>"timestamp without time zone", "label"=>"uninstall_date");
$GLOBALS["dbmap_open_ams"]["event_comments"]["comment_event"] = array("data_type"=>"text", "label"=>"comment_event");
$GLOBALS["dbmap_open_ams"]["event_comments"]["idadmin"] = array("data_type"=>"integer", "label"=>"idadmin");
$GLOBALS["dbmap_open_ams"]["event_comments"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["event_comments"]["ideventcomment"] = array("data_type"=>"bigint", "label"=>"ideventcomment");
$GLOBALS["dbmap_open_ams"]["event_comments"]["seconds"] = array("data_type"=>"integer", "label"=>"Segundos");
$GLOBALS["dbmap_open_ams"]["event_comments"]["start"] = array("data_type"=>"timestamp without time zone", "label"=>"Inicio");
$GLOBALS["dbmap_open_ams"]["event_comments"]["status"] = array("data_type"=>"smallint", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["event_comments"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["event_comments_attachments"]["idattachment"] = array("data_type"=>"integer", "label"=>"idattachment");
$GLOBALS["dbmap_open_ams"]["event_comments_attachments"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["event_comments_attachments"]["ideventcommentattach"] = array("data_type"=>"bigint", "label"=>"ideventcommentattach");
$GLOBALS["dbmap_open_ams"]["event_comments_attachments"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["events"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["events"]["code"] = array("data_type"=>"text", "label"=>"Código");
$GLOBALS["dbmap_open_ams"]["events"]["dateevent"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha evento");
$GLOBALS["dbmap_open_ams"]["events"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["events"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["events"]["idadmin"] = array("data_type"=>"integer", "label"=>"idadmin");
$GLOBALS["dbmap_open_ams"]["events"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["events"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["events"]["ideventtype"] = array("data_type"=>"integer", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["events"]["last_comment"] = array("data_type"=>"timestamp without time zone", "label"=>"Ultimo Comentario");
$GLOBALS["dbmap_open_ams"]["events"]["loaded"] = array("data_type"=>"timestamp without time zone", "label"=>"loaded");
$GLOBALS["dbmap_open_ams"]["events"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["events"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["events"]["status"] = array("data_type"=>"integer", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["events"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["events"]["zu"] = array("data_type"=>"bigint", "label"=>"Id Ref");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["code"] = array("data_type"=>"text", "label"=>"Código");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["dateevent"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Evento");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["db_name"] = array("data_type"=>"text", "label"=>"db_name");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["db_size"] = array("data_type"=>"real", "label"=>"db_size");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["db_type"] = array("data_type"=>"smallint", "label"=>"db_type");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["idadmin"] = array("data_type"=>"integer", "label"=>"idadmin");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["ideventtype"] = array("data_type"=>"integer", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["last_comment"] = array("data_type"=>"timestamp without time zone", "label"=>"Ultimo Comentario");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["loaded"] = array("data_type"=>"timestamp without time zone", "label"=>"loaded");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["status"] = array("data_type"=>"integer", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["events_dbsizes"]["zu"] = array("data_type"=>"bigint", "label"=>"IDZ");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["code"] = array("data_type"=>"text", "label"=>"Código");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["dateevent"] = array("data_type"=>"timestamp without time zone", "label"=>"dateevent");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["idadmin"] = array("data_type"=>"integer", "label"=>"idadmin");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["ideventtype"] = array("data_type"=>"integer", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["last_comment"] = array("data_type"=>"timestamp without time zone", "label"=>"Ultimo Comentario");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["loaded"] = array("data_type"=>"timestamp without time zone", "label"=>"loaded");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["status"] = array("data_type"=>"integer", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["uptime"] = array("data_type"=>"integer", "label"=>"uptime");
$GLOBALS["dbmap_open_ams"]["events_device_uptime"]["zu"] = array("data_type"=>"bigint", "label"=>"IDZ");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["code"] = array("data_type"=>"text", "label"=>"Código");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["dateevent"] = array("data_type"=>"timestamp without time zone", "label"=>"dateevent");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["drive"] = array("data_type"=>"text", "label"=>"drive");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["drive_free"] = array("data_type"=>"real", "label"=>"drive_free");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["drive_size"] = array("data_type"=>"real", "label"=>"drive_size");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["idadmin"] = array("data_type"=>"integer", "label"=>"idadmin");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["ideventtype"] = array("data_type"=>"integer", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["last_comment"] = array("data_type"=>"timestamp without time zone", "label"=>"Ultimo Comentario");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["loaded"] = array("data_type"=>"timestamp without time zone", "label"=>"loaded");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["status"] = array("data_type"=>"integer", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["events_diskspace"]["zu"] = array("data_type"=>"bigint", "label"=>"IDZ");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["code"] = array("data_type"=>"text", "label"=>"Código");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["dateevent"] = array("data_type"=>"timestamp without time zone", "label"=>"dateevent");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["idadmin"] = array("data_type"=>"integer", "label"=>"idadmin");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["ideventtype"] = array("data_type"=>"integer", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["job_date_create"] = array("data_type"=>"timestamp without time zone", "label"=>"job_date_create");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["job_description"] = array("data_type"=>"text", "label"=>"job_description");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["job_enabled"] = array("data_type"=>"boolean", "label"=>"job_enabled");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["job_name"] = array("data_type"=>"text", "label"=>"job_name");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["job_next_run"] = array("data_type"=>"timestamp without time zone", "label"=>"job_next_run");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["job_run_duration"] = array("data_type"=>"integer", "label"=>"job_run_duration");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["job_run_status"] = array("data_type"=>"smallint", "label"=>"job_run_status");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["last_comment"] = array("data_type"=>"timestamp without time zone", "label"=>"Ultimo Comentario");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["loaded"] = array("data_type"=>"timestamp without time zone", "label"=>"loaded");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["status"] = array("data_type"=>"integer", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["events_jobs"]["zu"] = array("data_type"=>"bigint", "label"=>"IDZ");
$GLOBALS["dbmap_open_ams"]["events_raid"]["account"] = array("data_type"=>"text", "label"=>"account");
$GLOBALS["dbmap_open_ams"]["events_raid"]["code"] = array("data_type"=>"text", "label"=>"code");
$GLOBALS["dbmap_open_ams"]["events_raid"]["dateevent"] = array("data_type"=>"timestamp without time zone", "label"=>"dateevent");
$GLOBALS["dbmap_open_ams"]["events_raid"]["description"] = array("data_type"=>"text", "label"=>"description");
$GLOBALS["dbmap_open_ams"]["events_raid"]["hostname"] = array("data_type"=>"inet", "label"=>"hostname");
$GLOBALS["dbmap_open_ams"]["events_raid"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["events_raid"]["idadmin"] = array("data_type"=>"integer", "label"=>"idadmin");
$GLOBALS["dbmap_open_ams"]["events_raid"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["events_raid"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["events_raid"]["ideventtype"] = array("data_type"=>"integer", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["events_raid"]["last_comment"] = array("data_type"=>"timestamp without time zone", "label"=>"last_comment");
$GLOBALS["dbmap_open_ams"]["events_raid"]["line_file"] = array("data_type"=>"integer", "label"=>"line_file");
$GLOBALS["dbmap_open_ams"]["events_raid"]["loaded"] = array("data_type"=>"timestamp without time zone", "label"=>"loaded");
$GLOBALS["dbmap_open_ams"]["events_raid"]["note"] = array("data_type"=>"text", "label"=>"note");
$GLOBALS["dbmap_open_ams"]["events_raid"]["priority"] = array("data_type"=>"integer", "label"=>"priority");
$GLOBALS["dbmap_open_ams"]["events_raid"]["status"] = array("data_type"=>"integer", "label"=>"status");
$GLOBALS["dbmap_open_ams"]["events_raid"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["events_raid"]["zu"] = array("data_type"=>"bigint", "label"=>"zu");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["autoclose_if_there_is_an_equal_even_noclosed_event"] = array("data_type"=>"integer", "label"=>"autoclose_if_there_is_an_equal_even_noclosed_event");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["auto_close_on_event_defined"] = array("data_type"=>"ARRAY", "label"=>"auto_close_on_event_defined");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["code"] = array("data_type"=>"text", "label"=>"Código");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["date_editable"] = array("data_type"=>"boolean", "label"=>"date_editable");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["enable_auto_close_on_event_defined"] = array("data_type"=>"boolean", "label"=>"enable_auto_close_on_event_defined");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["eventtype_groups"] = array("data_type"=>"ARRAY", "label"=>"eventtype_groups");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["expiration"] = array("data_type"=>"integer", "label"=>"expiration");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["ideventtype"] = array("data_type"=>"bigint", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["label"] = array("data_type"=>"text", "label"=>"label");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["manual"] = array("data_type"=>"boolean", "label"=>"manual");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["name"] = array("data_type"=>"text", "label"=>"name");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["notify_all_users"] = array("data_type"=>"boolean", "label"=>"notify_all_users");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["notify_closable"] = array("data_type"=>"boolean", "label"=>"notify_closable");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["notify_img"] = array("data_type"=>"text", "label"=>"notify_img");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["notify_snd"] = array("data_type"=>"text", "label"=>"notify_snd");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["notify_timeout"] = array("data_type"=>"integer", "label"=>"notify_timeout");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["treatment"] = array("data_type"=>"boolean", "label"=>"treatment");
$GLOBALS["dbmap_open_ams"]["eventtypes"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["activa"] = array("data_type"=>"text", "label"=>"fa_activa");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["idlista_precios"] = array("data_type"=>"bigint", "label"=>"idlista_precios");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["ip"] = array("data_type"=>"text", "label"=>"ip");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["principal"] = array("data_type"=>"text", "label"=>"fa_principal");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["productos"] = array("data_type"=>"integer", "label"=>"fa_productos");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["provincia"] = array("data_type"=>"text", "label"=>"provincia");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["sincronizado"] = array("data_type"=>"text", "label"=>"sincronizado");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["srv159_activa"] = array("data_type"=>"text", "label"=>"srv159_activa");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["srv159_principal"] = array("data_type"=>"text", "label"=>"srv159_principal");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["srv159_productos"] = array("data_type"=>"integer", "label"=>"srv159_productos");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["status"] = array("data_type"=>"text", "label"=>"estado");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["ts_lista_farmacia"] = array("data_type"=>"timestamp without time zone", "label"=>"fa_fecha");
$GLOBALS["dbmap_open_ams"]["farma_lista_precios_farmacias"]["ts_lista_srv159"] = array("data_type"=>"timestamp without time zone", "label"=>"srv159_fecha");
$GLOBALS["dbmap_open_ams"]["groups"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["groups"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["groups"]["iddivision"] = array("data_type"=>"bigint", "label"=>"iddivision");
$GLOBALS["dbmap_open_ams"]["groups"]["idgroup"] = array("data_type"=>"bigint", "label"=>"idgroup");
$GLOBALS["dbmap_open_ams"]["groups"]["name"] = array("data_type"=>"text", "label"=>"name");
$GLOBALS["dbmap_open_ams"]["groups"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["groups"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["identification_types"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["identification_types"]["ididtype"] = array("data_type"=>"bigint", "label"=>"Tipo de Identificación");
$GLOBALS["dbmap_open_ams"]["identification_types"]["name"] = array("data_type"=>"text", "label"=>"name");
$GLOBALS["dbmap_open_ams"]["identification_types"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["identification_types"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["interface_words"]["idword"] = array("data_type"=>"bigint", "label"=>"idword");
$GLOBALS["dbmap_open_ams"]["interface_words"]["notes"] = array("data_type"=>"text", "label"=>"notes");
$GLOBALS["dbmap_open_ams"]["interface_words"]["traslation"] = array("data_type"=>"text", "label"=>"traslation");
$GLOBALS["dbmap_open_ams"]["interface_words"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["interface_words"]["word"] = array("data_type"=>"text", "label"=>"word");
$GLOBALS["dbmap_open_ams"]["network_devices"]["agreement_code_provider"] = array("data_type"=>"text", "label"=>"agreement_code_provider");
$GLOBALS["dbmap_open_ams"]["network_devices"]["code_ref"] = array("data_type"=>"text", "label"=>"code_ref");
$GLOBALS["dbmap_open_ams"]["network_devices"]["connection_speed"] = array("data_type"=>"real", "label"=>"connection_speed");
$GLOBALS["dbmap_open_ams"]["network_devices"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["network_devices"]["equipment"] = array("data_type"=>"text", "label"=>"Equipo");
$GLOBALS["dbmap_open_ams"]["network_devices"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["network_devices"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["network_devices"]["idprovider"] = array("data_type"=>"integer", "label"=>"idprovider");
$GLOBALS["dbmap_open_ams"]["network_devices"]["installation_date"] = array("data_type"=>"timestamp without time zone", "label"=>"installation_date");
$GLOBALS["dbmap_open_ams"]["network_devices"]["ip"] = array("data_type"=>"inet", "label"=>"IP");
$GLOBALS["dbmap_open_ams"]["network_devices"]["mac"] = array("data_type"=>"macaddr", "label"=>"mac");
$GLOBALS["dbmap_open_ams"]["network_devices"]["mark"] = array("data_type"=>"text", "label"=>"Marca");
$GLOBALS["dbmap_open_ams"]["network_devices"]["model"] = array("data_type"=>"text", "label"=>"Modelo");
$GLOBALS["dbmap_open_ams"]["network_devices"]["monitored"] = array("data_type"=>"boolean", "label"=>"monitored");
$GLOBALS["dbmap_open_ams"]["network_devices"]["network_access_method"] = array("data_type"=>"text", "label"=>"network_access_method");
$GLOBALS["dbmap_open_ams"]["network_devices"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["network_devices"]["operability"] = array("data_type"=>"smallint", "label"=>"Operatividad");
$GLOBALS["dbmap_open_ams"]["network_devices"]["port"] = array("data_type"=>"smallint", "label"=>"port");
$GLOBALS["dbmap_open_ams"]["network_devices"]["pwd"] = array("data_type"=>"text", "label"=>"pwd");
$GLOBALS["dbmap_open_ams"]["network_devices"]["serial_number"] = array("data_type"=>"text", "label"=>"Número - Serie");
$GLOBALS["dbmap_open_ams"]["network_devices"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["network_devices"]["uninstall_date"] = array("data_type"=>"timestamp without time zone", "label"=>"uninstall_date");
$GLOBALS["dbmap_open_ams"]["network_devices"]["username"] = array("data_type"=>"text", "label"=>"username");
$GLOBALS["dbmap_open_ams"]["notification_area"]["body"] = array("data_type"=>"text", "label"=>"body");
$GLOBALS["dbmap_open_ams"]["notification_area"]["closable"] = array("data_type"=>"boolean", "label"=>"closable");
$GLOBALS["dbmap_open_ams"]["notification_area"]["idnotify"] = array("data_type"=>"bigint", "label"=>"idnotify");
$GLOBALS["dbmap_open_ams"]["notification_area"]["img"] = array("data_type"=>"text", "label"=>"img");
$GLOBALS["dbmap_open_ams"]["notification_area"]["sessionid"] = array("data_type"=>"text", "label"=>"sessionid");
$GLOBALS["dbmap_open_ams"]["notification_area"]["snd"] = array("data_type"=>"text", "label"=>"snd");
$GLOBALS["dbmap_open_ams"]["notification_area"]["timeout"] = array("data_type"=>"integer", "label"=>"timeout");
$GLOBALS["dbmap_open_ams"]["notification_area"]["title"] = array("data_type"=>"text", "label"=>"title");
$GLOBALS["dbmap_open_ams"]["notification_area"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["notification_area"]["urgency"] = array("data_type"=>"integer", "label"=>"urgency");
$GLOBALS["dbmap_open_ams"]["oams_table_columns"]["column_default"] = array("data_type"=>"text", "label"=>"column_default");
$GLOBALS["dbmap_open_ams"]["oams_table_columns"]["column_label"] = array("data_type"=>"text", "label"=>"column_label");
$GLOBALS["dbmap_open_ams"]["oams_table_columns"]["column_name"] = array("data_type"=>"text", "label"=>"column_name");
$GLOBALS["dbmap_open_ams"]["oams_table_columns"]["column_width"] = array("data_type"=>"text", "label"=>"column_width");
$GLOBALS["dbmap_open_ams"]["oams_table_columns"]["data_type"] = array("data_type"=>"text", "label"=>"data_type");
$GLOBALS["dbmap_open_ams"]["oams_table_columns"]["idword"] = array("data_type"=>"bigint", "label"=>"idword");
$GLOBALS["dbmap_open_ams"]["oams_table_columns"]["table_name"] = array("data_type"=>"text", "label"=>"table_name");
$GLOBALS["dbmap_open_ams"]["oams_table_columns"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["phone_providers"]["enable"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["phone_providers"]["idprovider"] = array("data_type"=>"bigint", "label"=>"idprovider");
$GLOBALS["dbmap_open_ams"]["phone_providers"]["provider"] = array("data_type"=>"text", "label"=>"provider");
$GLOBALS["dbmap_open_ams"]["phone_providers"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["phones"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["phones"]["ext"] = array("data_type"=>"text", "label"=>"Extensión");
$GLOBALS["dbmap_open_ams"]["phones"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["phones"]["idphone"] = array("data_type"=>"bigint", "label"=>"idphone");
$GLOBALS["dbmap_open_ams"]["phones"]["idphonetype"] = array("data_type"=>"integer", "label"=>"Tipo de teléfono");
$GLOBALS["dbmap_open_ams"]["phones"]["idprovider"] = array("data_type"=>"integer", "label"=>"Proveedor");
$GLOBALS["dbmap_open_ams"]["phones"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["phones"]["number"] = array("data_type"=>"text", "label"=>"Número");
$GLOBALS["dbmap_open_ams"]["phones"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["phone_types"]["idphonetype"] = array("data_type"=>"bigint", "label"=>"idphonetype");
$GLOBALS["dbmap_open_ams"]["phone_types"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["phone_types"]["type"] = array("data_type"=>"text", "label"=>"type");
$GLOBALS["dbmap_open_ams"]["providers"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["providers"]["address_ref"] = array("data_type"=>"text", "label"=>"Dirección - Ref.");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_end"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_end");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_failed_access_attempts"] = array("data_type"=>"smallint", "label"=>"admin_failed_access_attempts");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_ip"] = array("data_type"=>"text", "label"=>"admin_ip");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_level"] = array("data_type"=>"integer", "label"=>"admin_level");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_locked_date"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_locked_date");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_pwd"] = array("data_type"=>"text", "label"=>"admin_pwd");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_sessionid"] = array("data_type"=>"text", "label"=>"admin_sessionid");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_start"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_start");
$GLOBALS["dbmap_open_ams"]["providers"]["admin_username"] = array("data_type"=>"text", "label"=>"admin_username");
$GLOBALS["dbmap_open_ams"]["providers"]["birthday"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Nacimiento");
$GLOBALS["dbmap_open_ams"]["providers"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["providers"]["first_name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["providers"]["gender"] = array("data_type"=>"integer", "label"=>"gender");
$GLOBALS["dbmap_open_ams"]["providers"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["providers"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["providers"]["groups"] = array("data_type"=>"ARRAY", "label"=>"groups");
$GLOBALS["dbmap_open_ams"]["providers"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["providers"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["providers"]["ididtype"] = array("data_type"=>"integer", "label"=>"Tipo de Identificación");
$GLOBALS["dbmap_open_ams"]["providers"]["is_admin"] = array("data_type"=>"boolean", "label"=>"is_admin");
$GLOBALS["dbmap_open_ams"]["providers"]["last_name"] = array("data_type"=>"text", "label"=>"Apellido");
$GLOBALS["dbmap_open_ams"]["providers"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["providers"]["postal_code"] = array("data_type"=>"text", "label"=>"Código Postal");
$GLOBALS["dbmap_open_ams"]["providers"]["product_or_service"] = array("data_type"=>"text", "label"=>"product_or_service");
$GLOBALS["dbmap_open_ams"]["providers"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["sys_table_ts"]["table_name"] = array("data_type"=>"text", "label"=>"table_name");
$GLOBALS["dbmap_open_ams"]["sys_table_ts"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["sys_table_ts"]["tsz"] = array("data_type"=>"timestamp with time zone", "label"=>"tsz");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["account_name"] = array("data_type"=>"text", "label"=>"Farmacia");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["address_ref"] = array("data_type"=>"text", "label"=>"Dirección - Ref.");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["appointment"] = array("data_type"=>"text", "label"=>"Cargo");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["birthday"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Nacimiento");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["contact_name"] = array("data_type"=>"text", "label"=>"contact_name");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["enabled"] = array("data_type"=>"boolean", "label"=>"enabled");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["first_name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["geolink"] = array("data_type"=>"text", "label"=>"geolink");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["idaccountuser"] = array("data_type"=>"bigint", "label"=>"idaccountuser");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["last_name"] = array("data_type"=>"text", "label"=>"Apellido");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["view_account_contacts"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["code_ref"] = array("data_type"=>"text", "label"=>"code_ref");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["equipment"] = array("data_type"=>"text", "label"=>"Equipo");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["first_name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["idaccountstate"] = array("data_type"=>"integer", "label"=>"idaccountstate");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["idaccounttype"] = array("data_type"=>"integer", "label"=>"idaccounttype");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["iddivision"] = array("data_type"=>"integer", "label"=>"iddivision");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["ip"] = array("data_type"=>"inet", "label"=>"ip");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["last_name"] = array("data_type"=>"text", "label"=>"Apellido");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["mac"] = array("data_type"=>"macaddr", "label"=>"mac");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["mark"] = array("data_type"=>"text", "label"=>"Marca");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["model"] = array("data_type"=>"text", "label"=>"Modelo");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["monitored"] = array("data_type"=>"boolean", "label"=>"monitored");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["port"] = array("data_type"=>"smallint", "label"=>"port");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["pwd"] = array("data_type"=>"text", "label"=>"pwd");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["serial_number"] = array("data_type"=>"text", "label"=>"Número - Serie");
$GLOBALS["dbmap_open_ams"]["view_account_network_devices"]["username"] = array("data_type"=>"text", "label"=>"username");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["account_name"] = array("data_type"=>"text", "label"=>"Farmacia");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["address_ref"] = array("data_type"=>"text", "label"=>"Referencia Dirección");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["birthday"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Nacimiento");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["end_date"] = array("data_type"=>"timestamp without time zone", "label"=>"end_date");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["gender"] = array("data_type"=>"integer", "label"=>"Género");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["idaccountstate"] = array("data_type"=>"integer", "label"=>"Estado de la cuenta");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["idaccounttype"] = array("data_type"=>"integer", "label"=>"Tipo de cuenta");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["ididtype"] = array("data_type"=>"integer", "label"=>"Tipo de Identificación");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["postal_code"] = array("data_type"=>"text", "label"=>"Código postal");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["start_date"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha de inicio");
$GLOBALS["dbmap_open_ams"]["view_accounts"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["account_name"] = array("data_type"=>"text", "label"=>"Farmacia");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["address_ref"] = array("data_type"=>"text", "label"=>"Dirección - Ref.");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["appointment"] = array("data_type"=>"text", "label"=>"Cargo");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["birthday"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Nacimiento");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["contact_name"] = array("data_type"=>"text", "label"=>"Técnico Asignado");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["enabled"] = array("data_type"=>"boolean", "label"=>"enabled");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["first_name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["geolink"] = array("data_type"=>"text", "label"=>"geolink");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["idaccountuser"] = array("data_type"=>"bigint", "label"=>"idaccountuser");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["last_name"] = array("data_type"=>"text", "label"=>"Apellido");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["view_accounts_oams_assigned"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["account_pwd"] = array("data_type"=>"text", "label"=>"account_pwd");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["account_user"] = array("data_type"=>"text", "label"=>"account_user");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["appointment"] = array("data_type"=>"text", "label"=>"Cargo");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["enabled_account"] = array("data_type"=>"boolean", "label"=>"enabled_account");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["enabled_user"] = array("data_type"=>"boolean", "label"=>"enabled_user");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["first_name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["idaccount"] = array("data_type"=>"bigint", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_accounts_users_pwd"]["last_name"] = array("data_type"=>"text", "label"=>"Apellido");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["account_identification"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["account_name"] = array("data_type"=>"text", "label"=>"Farmacia");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["account_pwd"] = array("data_type"=>"text", "label"=>"account_pwd");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["account_user"] = array("data_type"=>"text", "label"=>"account_user");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["appointment"] = array("data_type"=>"text", "label"=>"Cargo");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["idaccount"] = array("data_type"=>"bigint", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["idaccountuser"] = array("data_type"=>"bigint", "label"=>"idaccountuser");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["priority"] = array("data_type"=>"integer", "label"=>"Prioridad");
$GLOBALS["dbmap_open_ams"]["view_account_users"]["user_name"] = array("data_type"=>"text", "label"=>"user_name");
$GLOBALS["dbmap_open_ams"]["view_admins"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["view_admins"]["address_ref"] = array("data_type"=>"text", "label"=>"Dirección - Ref.");
$GLOBALS["dbmap_open_ams"]["view_admins"]["admin_end"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_end");
$GLOBALS["dbmap_open_ams"]["view_admins"]["admin_ip"] = array("data_type"=>"text", "label"=>"admin_ip");
$GLOBALS["dbmap_open_ams"]["view_admins"]["admin_level"] = array("data_type"=>"integer", "label"=>"admin_level");
$GLOBALS["dbmap_open_ams"]["view_admins"]["admin_name"] = array("data_type"=>"text", "label"=>"Administrador");
$GLOBALS["dbmap_open_ams"]["view_admins"]["admin_pwd"] = array("data_type"=>"text", "label"=>"admin_pwd");
$GLOBALS["dbmap_open_ams"]["view_admins"]["admin_sessionid"] = array("data_type"=>"text", "label"=>"admin_sessionid");
$GLOBALS["dbmap_open_ams"]["view_admins"]["admin_start"] = array("data_type"=>"timestamp without time zone", "label"=>"admin_start");
$GLOBALS["dbmap_open_ams"]["view_admins"]["admin_username"] = array("data_type"=>"text", "label"=>"admin_username");
$GLOBALS["dbmap_open_ams"]["view_admins"]["birthday"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Nacimiento");
$GLOBALS["dbmap_open_ams"]["view_admins"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["view_admins"]["gender"] = array("data_type"=>"integer", "label"=>"gender");
$GLOBALS["dbmap_open_ams"]["view_admins"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["view_admins"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["view_admins"]["groups"] = array("data_type"=>"ARRAY", "label"=>"groups");
$GLOBALS["dbmap_open_ams"]["view_admins"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_admins"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_admins"]["ididtype"] = array("data_type"=>"integer", "label"=>"Tipo de Identificación");
$GLOBALS["dbmap_open_ams"]["view_admins"]["is_admin"] = array("data_type"=>"boolean", "label"=>"is_admin");
$GLOBALS["dbmap_open_ams"]["view_admins"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["view_admins"]["postal_code"] = array("data_type"=>"text", "label"=>"Código Postal");
$GLOBALS["dbmap_open_ams"]["view_contact_groups"]["description"] = array("data_type"=>"text", "label"=>"description");
$GLOBALS["dbmap_open_ams"]["view_contact_groups"]["enabled"] = array("data_type"=>"boolean", "label"=>"enabled");
$GLOBALS["dbmap_open_ams"]["view_contact_groups"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_contact_groups"]["idcontactgroup"] = array("data_type"=>"bigint", "label"=>"idcontactgroup");
$GLOBALS["dbmap_open_ams"]["view_contact_groups"]["idgroup"] = array("data_type"=>"bigint", "label"=>"idgroup");
$GLOBALS["dbmap_open_ams"]["view_contact_groups"]["name"] = array("data_type"=>"text", "label"=>"name");
$GLOBALS["dbmap_open_ams"]["view_contact_groups"]["note"] = array("data_type"=>"text", "label"=>"note");
$GLOBALS["dbmap_open_ams"]["view_contact_groups"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["view_contact_groups_they_belong"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["view_contact_groups_they_belong"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["view_contact_groups_they_belong"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_contact_groups_they_belong"]["idgroup"] = array("data_type"=>"bigint", "label"=>"idgroup");
$GLOBALS["dbmap_open_ams"]["view_contact_groups_they_belong"]["ismember"] = array("data_type"=>"boolean", "label"=>"Es Miembro");
$GLOBALS["dbmap_open_ams"]["view_contact_groups_they_belong"]["name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["view_contact_groups_they_belong"]["note"] = array("data_type"=>"text", "label"=>"Nota");
$GLOBALS["dbmap_open_ams"]["view_contact_groups_they_belong"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["address_ref"] = array("data_type"=>"text", "label"=>"Dirección Referencia");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["birthday"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Nacimiento");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["contact_name"] = array("data_type"=>"text", "label"=>"Nombre");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["gender"] = array("data_type"=>"integer", "label"=>"Género");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["geox"] = array("data_type"=>"double precision", "label"=>"Latitud");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["geoy"] = array("data_type"=>"double precision", "label"=>"Longitud");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["groups"] = array("data_type"=>"ARRAY", "label"=>"Grupos");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["ididtype"] = array("data_type"=>"integer", "label"=>"Tipo de Identificación");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["note"] = array("data_type"=>"text", "label"=>"note");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["postal_code"] = array("data_type"=>"text", "label"=>"postal_code");
$GLOBALS["dbmap_open_ams"]["view_contacts"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"ts");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["account_name"] = array("data_type"=>"text", "label"=>"Farmacia");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["accounttype"] = array("data_type"=>"text", "label"=>"Tipo de cuenta");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["agreement_code_provider"] = array("data_type"=>"text", "label"=>"agreement_code_provider");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["code_ref"] = array("data_type"=>"text", "label"=>"Código de referencia");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["equipment"] = array("data_type"=>"text", "label"=>"Equipo");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["idaccountstate"] = array("data_type"=>"integer", "label"=>"idaccountstate");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["idaccounttype"] = array("data_type"=>"integer", "label"=>"idaccounttype");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["idcontact"] = array("data_type"=>"bigint", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["identification"] = array("data_type"=>"text", "label"=>"Identificación");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["idequipment"] = array("data_type"=>"bigint", "label"=>"idequipment");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["idprovider"] = array("data_type"=>"integer", "label"=>"idprovider");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["installation_date"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Instalación");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["mark"] = array("data_type"=>"text", "label"=>"Marca");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["model"] = array("data_type"=>"text", "label"=>"Modelo");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["note"] = array("data_type"=>"text", "label"=>"Notas");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["oams_assigned"] = array("data_type"=>"text", "label"=>"Técnico Asignado");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["operability"] = array("data_type"=>"smallint", "label"=>"Operatividad");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["serial_number"] = array("data_type"=>"text", "label"=>"Número - Serie");
$GLOBALS["dbmap_open_ams"]["view_equipments"]["uninstall_date"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Desinstalación");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["account_name"] = array("data_type"=>"text", "label"=>"Farmacia");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["code"] = array("data_type"=>"text", "label"=>"Código");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["dateevent"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Evento");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["description"] = array("data_type"=>"text", "label"=>"Descripción");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["first_name"] = array("data_type"=>"text", "label"=>"Farmacia");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["ideventtype"] = array("data_type"=>"integer", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["label"] = array("data_type"=>"text", "label"=>"Evento");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["last_comment"] = array("data_type"=>"timestamp without time zone", "label"=>"Ultimo Comentario");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["last_name"] = array("data_type"=>"text", "label"=>"Apellido");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["oams_assigned"] = array("data_type"=>"text", "label"=>"Técnico Asignado");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["priority"] = array("data_type"=>"integer", "label"=>"P");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["status"] = array("data_type"=>"integer", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["status_label"] = array("data_type"=>"text", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["view_events_monitor"]["zu"] = array("data_type"=>"bigint", "label"=>"ID");
$GLOBALS["dbmap_open_ams"]["view_events_with_eventtypes_detail"]["auto_close_on_event_defined"] = array("data_type"=>"ARRAY", "label"=>"auto_close_on_event_defined");
$GLOBALS["dbmap_open_ams"]["view_events_with_eventtypes_detail"]["dateevent"] = array("data_type"=>"timestamp without time zone", "label"=>"dateevent");
$GLOBALS["dbmap_open_ams"]["view_events_with_eventtypes_detail"]["enable_auto_close_on_event_defined"] = array("data_type"=>"boolean", "label"=>"enable_auto_close_on_event_defined");
$GLOBALS["dbmap_open_ams"]["view_events_with_eventtypes_detail"]["idaccount"] = array("data_type"=>"integer", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["view_events_with_eventtypes_detail"]["idevent"] = array("data_type"=>"bigint", "label"=>"idevent");
$GLOBALS["dbmap_open_ams"]["view_events_with_eventtypes_detail"]["ideventtype"] = array("data_type"=>"integer", "label"=>"ideventtype");
$GLOBALS["dbmap_open_ams"]["view_events_with_eventtypes_detail"]["status"] = array("data_type"=>"integer", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["view_events_with_eventtypes_detail"]["zu"] = array("data_type"=>"bigint", "label"=>"IDZ");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["account"] = array("data_type"=>"text", "label"=>"Oficina");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["account_name"] = array("data_type"=>"text", "label"=>"Farmacia");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["activa"] = array("data_type"=>"text", "label"=>"Activa Farma");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["address"] = array("data_type"=>"text", "label"=>"Dirección");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["contact_name"] = array("data_type"=>"text", "label"=>"Técnico Responsable");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["enabled"] = array("data_type"=>"boolean", "label"=>"Habilitado");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["estado"] = array("data_type"=>"text", "label"=>"Estado");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["geolink"] = array("data_type"=>"text", "label"=>"Link Geolocalización");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["idaccount"] = array("data_type"=>"bigint", "label"=>"idaccount");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["idaccountuser"] = array("data_type"=>"bigint", "label"=>"idaccountuser");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["idcontact"] = array("data_type"=>"integer", "label"=>"idcontact");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["ip"] = array("data_type"=>"text", "label"=>"ip");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["note"] = array("data_type"=>"text", "label"=>"note");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["principal"] = array("data_type"=>"text", "label"=>"Principal Farma");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["productos"] = array("data_type"=>"integer", "label"=>"Productos Farma");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["provincia"] = array("data_type"=>"text", "label"=>"provincia");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["sincronizado"] = array("data_type"=>"text", "label"=>"Farma = SRV159");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["srv159_activa"] = array("data_type"=>"text", "label"=>"Activa SRV159");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["srv159_principal"] = array("data_type"=>"text", "label"=>"Principal SRV159");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["srv159_productos"] = array("data_type"=>"integer", "label"=>"Productos SRV159");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["status"] = array("data_type"=>"text", "label"=>"Estado Farma");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["tecnico"] = array("data_type"=>"text", "label"=>"Técnico Responsable");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["ts"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Tabla");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["ts_farmacia"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha Farma");
$GLOBALS["dbmap_open_ams"]["view_farma_lista_precios"]["ts_server159"] = array("data_type"=>"timestamp without time zone", "label"=>"Fecha SRV159");

?>