/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./src/service-worker.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./src/node_modules/@sapper/service-worker.js":
/*!****************************************************!*\
  !*** ./src/node_modules/@sapper/service-worker.js ***!
  \****************************************************/
/*! exports provided: timestamp, files, assets, shell, routes */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"timestamp\", function() { return timestamp; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"files\", function() { return files; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"assets\", function() { return files; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"shell\", function() { return shell; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"routes\", function() { return routes; });\n// This file is generated by Sapper — do not edit it!\nconst timestamp = 1596070459588;\n\nconst files = [\n\t\"service-worker-index.html\",\n\t\"css/bulma/bulma.min.css\",\n\t\"css/fontawesome/css/all.css\",\n\t\"css/fontawesome/css/all.min.css\",\n\t\"css/fontawesome/css/brands.css\",\n\t\"css/fontawesome/css/brands.min.css\",\n\t\"css/fontawesome/css/fontawesome.css\",\n\t\"css/fontawesome/css/fontawesome.min.css\",\n\t\"css/fontawesome/css/regular.css\",\n\t\"css/fontawesome/css/regular.min.css\",\n\t\"css/fontawesome/css/solid.css\",\n\t\"css/fontawesome/css/solid.min.css\",\n\t\"css/fontawesome/css/svg-with-js.css\",\n\t\"css/fontawesome/css/svg-with-js.min.css\",\n\t\"css/fontawesome/css/v4-shims.css\",\n\t\"css/fontawesome/css/v4-shims.min.css\",\n\t\"css/fontawesome/webfonts/fa-brands-400.eot\",\n\t\"css/fontawesome/webfonts/fa-brands-400.svg\",\n\t\"css/fontawesome/webfonts/fa-brands-400.ttf\",\n\t\"css/fontawesome/webfonts/fa-brands-400.woff\",\n\t\"css/fontawesome/webfonts/fa-brands-400.woff2\",\n\t\"css/fontawesome/webfonts/fa-regular-400.eot\",\n\t\"css/fontawesome/webfonts/fa-regular-400.svg\",\n\t\"css/fontawesome/webfonts/fa-regular-400.ttf\",\n\t\"css/fontawesome/webfonts/fa-regular-400.woff\",\n\t\"css/fontawesome/webfonts/fa-regular-400.woff2\",\n\t\"css/fontawesome/webfonts/fa-solid-900.eot\",\n\t\"css/fontawesome/webfonts/fa-solid-900.svg\",\n\t\"css/fontawesome/webfonts/fa-solid-900.ttf\",\n\t\"css/fontawesome/webfonts/fa-solid-900.woff\",\n\t\"css/fontawesome/webfonts/fa-solid-900.woff2\",\n\t\"favicon/android-icon-144x144.png\",\n\t\"favicon/android-icon-192x192.png\",\n\t\"favicon/android-icon-36x36.png\",\n\t\"favicon/android-icon-48x48.png\",\n\t\"favicon/android-icon-72x72.png\",\n\t\"favicon/android-icon-96x96.png\",\n\t\"favicon/apple-icon-114x114.png\",\n\t\"favicon/apple-icon-120x120.png\",\n\t\"favicon/apple-icon-144x144.png\",\n\t\"favicon/apple-icon-152x152.png\",\n\t\"favicon/apple-icon-180x180.png\",\n\t\"favicon/apple-icon-57x57.png\",\n\t\"favicon/apple-icon-60x60.png\",\n\t\"favicon/apple-icon-72x72.png\",\n\t\"favicon/apple-icon-76x76.png\",\n\t\"favicon/apple-icon-precomposed.png\",\n\t\"favicon/apple-icon.png\",\n\t\"favicon/favicon-16x16.png\",\n\t\"favicon/favicon-32x32.png\",\n\t\"favicon/favicon-96x96.png\",\n\t\"favicon/favicon.ico\",\n\t\"favicon/ms-icon-144x144.png\",\n\t\"favicon/ms-icon-150x150.png\",\n\t\"favicon/ms-icon-310x310.png\",\n\t\"favicon/ms-icon-70x70.png\",\n\t\"favicon.png\",\n\t\"global.css\",\n\t\"logo-192.png\",\n\t\"logo-512.png\",\n\t\"manifest.json\",\n\t\"successkid.jpg\"\n];\n // legacy\n\nconst shell = [\n\t\"client/332bb9ae79c1d6cb829e/0.0.js\",\n\t\"client/332bb9ae79c1d6cb829e/about.about.js\",\n\t\"client/332bb9ae79c1d6cb829e/blog.blog.js\",\n\t\"client/332bb9ae79c1d6cb829e/blog_$slug.blog_$slug.js\",\n\t\"client/332bb9ae79c1d6cb829e/contact.contact.js\",\n\t\"client/332bb9ae79c1d6cb829e/contacts.contacts.js\",\n\t\"client/332bb9ae79c1d6cb829e/contact~contacts~home~monitor~vehicle~vehicles.contact~contacts~home~monitor~vehicle~vehicles.js\",\n\t\"client/332bb9ae79c1d6cb829e/contact~contacts~vehicle.contact~contacts~vehicle.js\",\n\t\"client/332bb9ae79c1d6cb829e/contact~vehicle.contact~vehicle.js\",\n\t\"client/332bb9ae79c1d6cb829e/home.home.js\",\n\t\"client/332bb9ae79c1d6cb829e/index.index.js\",\n\t\"client/332bb9ae79c1d6cb829e/main.js\",\n\t\"client/332bb9ae79c1d6cb829e/monitor.monitor.js\",\n\t\"client/332bb9ae79c1d6cb829e/register.register.js\",\n\t\"client/332bb9ae79c1d6cb829e/vehicle.vehicle.js\",\n\t\"client/332bb9ae79c1d6cb829e/vehicles.vehicles.js\",\n\t\"client/332bb9ae79c1d6cb829e/vendors~monitor.vendors~monitor.js\",\n\t\"client/icon_144x144.13f216165df2f58fa919bf4077c15b04.png\",\n\t\"client/icon_192x192.801dea800a99080ba5a620ca9bdaf47f.png\",\n\t\"client/icon_36x36.ad0fdfc7e6d49ca792127a34d66c4833.png\",\n\t\"client/icon_48x48.2fb01863ddda9d70288fd46bdf682896.png\",\n\t\"client/icon_72x72.08656ccc73f1766e11baf8fe27cd10ca.png\",\n\t\"client/icon_96x96.3638662037b1397439b974c121e82dd3.png\",\n\t\"client/manifest.91ba560b6e5f1ac6d699f2624258c875.json\"\n];\n\nconst routes = [\n\t{ pattern: /^\\/$/ },\n\t{ pattern: /^\\/contacts\\/?$/ },\n\t{ pattern: /^\\/register\\/?$/ },\n\t{ pattern: /^\\/vehicles\\/?$/ },\n\t{ pattern: /^\\/contact\\/?$/ },\n\t{ pattern: /^\\/monitor\\/?$/ },\n\t{ pattern: /^\\/vehicle\\/?$/ },\n\t{ pattern: /^\\/about\\/?$/ },\n\t{ pattern: /^\\/blog\\/?$/ },\n\t{ pattern: /^\\/blog\\/([^\\/]+?)\\/?$/ },\n\t{ pattern: /^\\/home\\/?$/ }\n];\n\n//# sourceURL=webpack:///./src/node_modules/@sapper/service-worker.js?");

/***/ }),

/***/ "./src/service-worker.js":
/*!*******************************!*\
  !*** ./src/service-worker.js ***!
  \*******************************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @sapper/service-worker */ \"./src/node_modules/@sapper/service-worker.js\");\n\n\n/*\nasync function ApiToCache(event) {\n\nlet cache = await caches.open('myapi-cache');\nlet response = await cache.match(event.request);\nlet resp = response || await fetch(event.request);\nawait cache.put(event.request, resp.clone());\nreturn resp;\n\n}\n*/\n\nconst ASSETS = `cache${_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`;\n\n// `shell` is an array of all the files generated by the bundler,\n// `files` is an array of everything in the `static` directory\nconst to_cache = _sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"shell\"].concat(_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"files\"]);\nconst cached = new Set(to_cache);\n\nself.addEventListener('install', event => {\n\tevent.waitUntil(\n\t\tcaches\n\t\t.open(ASSETS)\n\t\t.then(cache => cache.addAll(to_cache))\n\t\t.then(() => {\n\t\t\tself.skipWaiting();\n\t\t})\n\t);\n});\n\nself.addEventListener('activate', event => {\n\tevent.waitUntil(\n\t\tcaches.keys().then(async keys => {\n\t\t\t// delete old caches\n\t\t\tfor (const key of keys) {\n\t\t\t\tif (key !== ASSETS) await caches.delete(key);\n\t\t\t}\n\n\t\t\tself.clients.claim();\n\t\t})\n\t);\n});\n\nself.addEventListener('fetch', async (event) => {\n\n\tif (event.request.method !== 'GET' || event.request.headers.has('range')) return;\n\tconst url = new URL(event.request.url);\n\t// don't try to handle e.g. data: URIs\n\tif (!url.protocol.startsWith('http')) return;\n\t// ignore dev server requests\n\tif (url.hostname === self.location.hostname && url.port !== self.location.port) return;\n\n\t// always serve static files and bundler-generated assets from cache\n\tif (url.host === self.location.host && cached.has(url.pathname)) {\n\n\t\tevent.respondWith(caches.match(event.request));\n\t\treturn;\n\t}\n\n\t// for pages, you might want to serve a shell `service-worker-index.html` file,\n\t// which Sapper has generated for you. It's not right for every\n\t// app, but if it's right for yours then uncomment this section\n\t/*\n\tif (url.origin === self.origin && routes.find(route => route.pattern.test(url.pathname))) {\n\t\tevent.respondWith(caches.match('/service-worker-index.html'));\n\t\treturn;\n\t}\n\t*/\n\n\tif (event.request.cache === 'only-if-cached') return;\n\n\t// for everything else, try the network first, falling back to\n\t// cache if the user is offline. (If the pages never change, you\n\t// might prefer a cache-first approach to a network-first one.)\n\tevent.respondWith(\n\t\tcaches\n\t\t.open(`offline${_sapper_service_worker__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`)\n\t\t.then(async cache => {\n\t\t\ttry {\n\t\t\t\tconst response = await fetch(event.request);\n\t\t\t\tcache.put(event.request, response.clone());\n\t\t\t\treturn response;\n\t\t\t} catch (err) {\n\t\t\t\tconst response = await cache.match(event.request);\n\t\t\t\tif (response) return response;\n\n\t\t\t\tthrow err;\n\t\t\t}\n\t\t})\n\t);\n\n\n\t//await event.respondWith(ApiToCache(event));\n\n\n});\n\n//# sourceURL=webpack:///./src/service-worker.js?");

/***/ })

/******/ });